/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import DAO.ComidaDAO;
import Model.Pessoa;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.util.Set;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuário
 */
public class CadastroComidaView extends javax.swing.JFrame {

    private ComidaDAO comidaDAO = new ComidaDAO();
    
    public CadastroComidaView(){
        initComponents();       
        Color backGroundColor=  new Color(221,221,221);
        this.getContentPane().setBackground(backGroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfNomeComida = new javax.swing.JTextField();
        cmbTipoComida = new javax.swing.JComboBox<>();
        tfrelComidaAgua = new javax.swing.JTextField();
        btnSalvarCadastroComida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTipoPessoa = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cmbDetalheCarne = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro8 = new javax.swing.JMenu();
        btnCadastroPessoa5 = new javax.swing.JMenuItem();
        btnCadastroComida8 = new javax.swing.JMenuItem();
        btnRefeicao8 = new javax.swing.JMenu();
        miRefNovaView2 = new javax.swing.JMenuItem();
        btnRefeicaoHistoricoView2 = new javax.swing.JMenuItem();
        btnRelatório8 = new javax.swing.JMenu();
        btnRelatorioPessoasView2 = new javax.swing.JMenuItem();
        btnRelatorioComidaView2 = new javax.swing.JMenuItem();
        miCalcularImpacto3 = new javax.swing.JMenu();
        miCalcImpacView2 = new javax.swing.JMenuItem();
        miVisualizarImpactoView2 = new javax.swing.JMenuItem();
        miCalcularDieta4 = new javax.swing.JMenu();
        miCalcularDietaView2 = new javax.swing.JMenuItem();
        miVisualizarDietaView2 = new javax.swing.JMenuItem();
        miRankingGeral5 = new javax.swing.JMenu();
        miRankingGeralView2 = new javax.swing.JMenuItem();
        mnRemPesView1 = new javax.swing.JMenu();
        miRemPesView1 = new javax.swing.JMenuItem();
        miRemRefeicaoView2 = new javax.swing.JMenuItem();

        jLabel2.setText("jLabel2");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenuItem4.setText("jMenuItem4");

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Tipo de Comida:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Razão Litros por Gramas:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Nome:");

        tfNomeComida.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfNomeComidaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfNomeComidaFocusLost(evt);
            }
        });
        tfNomeComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNomeComidaActionPerformed(evt);
            }
        });

        cmbTipoComida.setBackground(new java.awt.Color(37, 201, 228));
        cmbTipoComida.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma das opções", "Carne", "Grão", "Vegetal" }));
        cmbTipoComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoComidaActionPerformed(evt);
            }
        });

        tfrelComidaAgua.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfrelComidaAguaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfrelComidaAguaFocusLost(evt);
            }
        });

        btnSalvarCadastroComida.setText("Salvar");
        btnSalvarCadastroComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarCadastroComidaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro Comida");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Escolha a Pessoa: ");

        cmbTipoPessoa.setBackground(new java.awt.Color(37, 201, 228));
        cmbTipoPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipoPessoaActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Detalhes:");

        cmbDetalheCarne.setBackground(new java.awt.Color(37, 201, 228));
        cmbDetalheCarne.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Escolha uma das opções", "100% Natural / Orgânico", "Uso de Técnicas Nocivas" }));
        cmbDetalheCarne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDetalheCarneActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(42, 187, 242));

        mnCadastro8.setText("Cadastro");
        mnCadastro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastro8ActionPerformed(evt);
            }
        });

        btnCadastroPessoa5.setText("Cadastro Pessoa");
        btnCadastroPessoa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoa5ActionPerformed(evt);
            }
        });
        mnCadastro8.add(btnCadastroPessoa5);

        btnCadastroComida8.setText("Cadastro Comida");
        btnCadastroComida8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroComida8ActionPerformed(evt);
            }
        });
        mnCadastro8.add(btnCadastroComida8);

        jMenuBar1.add(mnCadastro8);

        btnRefeicao8.setText("Refeição");
        btnRefeicao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicao8ActionPerformed(evt);
            }
        });

        miRefNovaView2.setText("Nova Refeição");
        miRefNovaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRefNovaView2ActionPerformed(evt);
            }
        });
        btnRefeicao8.add(miRefNovaView2);

        btnRefeicaoHistoricoView2.setText("Histórico Refeição");
        btnRefeicaoHistoricoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicaoHistoricoView2ActionPerformed(evt);
            }
        });
        btnRefeicao8.add(btnRefeicaoHistoricoView2);

        jMenuBar1.add(btnRefeicao8);

        btnRelatório8.setText("Relatório");

        btnRelatorioPessoasView2.setText("Pessoas");
        btnRelatorioPessoasView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPessoasView2ActionPerformed(evt);
            }
        });
        btnRelatório8.add(btnRelatorioPessoasView2);

        btnRelatorioComidaView2.setText("Comida");
        btnRelatorioComidaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioComidaView2ActionPerformed(evt);
            }
        });
        btnRelatório8.add(btnRelatorioComidaView2);

        jMenuBar1.add(btnRelatório8);

        miCalcularImpacto3.setText("Impacto");

        miCalcImpacView2.setText("Calcular Impacto");
        miCalcImpacView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcImpacView2ActionPerformed(evt);
            }
        });
        miCalcularImpacto3.add(miCalcImpacView2);

        miVisualizarImpactoView2.setText("Visualizar Impacto");
        miVisualizarImpactoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarImpactoView2ActionPerformed(evt);
            }
        });
        miCalcularImpacto3.add(miVisualizarImpactoView2);

        jMenuBar1.add(miCalcularImpacto3);

        miCalcularDieta4.setText("Dieta");
        miCalcularDieta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDieta4ActionPerformed(evt);
            }
        });

        miCalcularDietaView2.setText("Calcular Dieta");
        miCalcularDietaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDietaView2ActionPerformed(evt);
            }
        });
        miCalcularDieta4.add(miCalcularDietaView2);

        miVisualizarDietaView2.setText("Visualizar Dieta");
        miVisualizarDietaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarDietaView2ActionPerformed(evt);
            }
        });
        miCalcularDieta4.add(miVisualizarDietaView2);

        jMenuBar1.add(miCalcularDieta4);

        miRankingGeral5.setText("Ranking");

        miRankingGeralView2.setText("Ranking Geral");
        miRankingGeralView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRankingGeralView2ActionPerformed(evt);
            }
        });
        miRankingGeral5.add(miRankingGeralView2);

        jMenuBar1.add(miRankingGeral5);

        mnRemPesView1.setText("Remover");

        miRemPesView1.setText("Remover Pessoa");
        miRemPesView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemPesView1ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemPesView1);

        miRemRefeicaoView2.setText("Remover Refeição");
        miRemRefeicaoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemRefeicaoView2ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemRefeicaoView2);

        jMenuBar1.add(mnRemPesView1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(363, 363, 363)
                        .addComponent(btnSalvarCadastroComida))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfrelComidaAgua, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tfNomeComida))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cmbDetalheCarne, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(cmbTipoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(147, 147, 147)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbTipoPessoa, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbTipoPessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbTipoComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbDetalheCarne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfNomeComida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfrelComidaAgua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(btnSalvarCadastroComida)
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void tfNomeComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNomeComidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNomeComidaActionPerformed

    private void tfNomeComidaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeComidaFocusGained
        
    }//GEN-LAST:event_tfNomeComidaFocusGained

    private void tfNomeComidaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfNomeComidaFocusLost
       
    }//GEN-LAST:event_tfNomeComidaFocusLost

    private void tfrelComidaAguaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfrelComidaAguaFocusGained
        
    }//GEN-LAST:event_tfrelComidaAguaFocusGained

    private void tfrelComidaAguaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfrelComidaAguaFocusLost
        
    }//GEN-LAST:event_tfrelComidaAguaFocusLost
    
    public void adicionarAcaoBotaoCadastroComida(ActionListener acao){
        btnSalvarCadastroComida.addActionListener(acao);
    }
    
    public String getNomeComida(){
        return tfNomeComida.getText();
    }
    
    public void exibirTela(){
        setVisible(true);
    }
    
    public String getTipoComida(){
        String tipoComida = "";
        
        if(cmbTipoComida.getSelectedItem().equals("Carne")){
            tipoComida = "Carne";
        }else if(cmbTipoComida.getSelectedItem().equals("Grão")){
            tipoComida = "Grão";
        }else if(cmbTipoComida.getSelectedItem().equals("Vegetal")){
            tipoComida = "Vegetal";
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um Tipo de Comida Válido");
        }
        return tipoComida;
    }
    
    public String getDetalheComida(){
        String detalheComida = "";        
        
        if(cmbDetalheCarne.getSelectedItem().equals("100% Natural / Orgânico")){
           detalheComida = "100% Natural / Orgânico";
            
        }else if(cmbDetalheCarne.getSelectedItem().equals("Uso de Técnicas Nocivas")){
            detalheComida = "Uso de Técnicas Nocivas";       
        }else{
            JOptionPane.showMessageDialog(null, "Detalhe o tipo de Comida");
        }
                    
        return detalheComida;
    }
    
    public String getRelComidaAgua(){           
        return tfrelComidaAgua.getText();
    }
    
    public void addCMBPessoas(Pessoa p){
        cmbTipoPessoa.addItem(p);
    }
    
    public Pessoa getPessoa(){
        return (Pessoa) cmbTipoPessoa.getSelectedItem();
    }
    
    
    private void btnSalvarCadastroComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarCadastroComidaActionPerformed
       
    }//GEN-LAST:event_btnSalvarCadastroComidaActionPerformed
         
    private void cmbTipoPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoPessoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTipoPessoaActionPerformed

    private void cmbTipoComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipoComidaActionPerformed
       
    }//GEN-LAST:event_cmbTipoComidaActionPerformed

    private void cmbDetalheCarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDetalheCarneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbDetalheCarneActionPerformed

    private void btnCadastroPessoa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoa5ActionPerformed
        CadastroPessoaController cadPessoaController = new CadastroPessoaController(new CadastroPessoaView());
        cadPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroPessoa5ActionPerformed

    private void btnCadastroComida8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroComida8ActionPerformed
        CadastroComidaController cadComidaController = new CadastroComidaController(new CadastroComidaView());
        cadComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroComida8ActionPerformed

    private void mnCadastro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastro8ActionPerformed
        //Nada
    }//GEN-LAST:event_mnCadastro8ActionPerformed

    private void miRefNovaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRefNovaView2ActionPerformed
        RefeicaoNovaController refNovaController = new RefeicaoNovaController(new RefeicaoNovaView());
        refNovaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRefNovaView2ActionPerformed

    private void btnRefeicaoHistoricoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicaoHistoricoView2ActionPerformed
        RefeicaoHistoricoController refHistController = new RefeicaoHistoricoController(new RefeicaoHistoricoView());
        refHistController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRefeicaoHistoricoView2ActionPerformed

    private void btnRefeicao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicao8ActionPerformed
        //Nada
    }//GEN-LAST:event_btnRefeicao8ActionPerformed

    private void btnRelatorioPessoasView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPessoasView2ActionPerformed
        RelatorioPessoaController relComidaController = new RelatorioPessoaController(new RelatorioPessoaView());
        relComidaController.exibeTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioPessoasView2ActionPerformed

    private void btnRelatorioComidaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioComidaView2ActionPerformed
        RelatorioComidaController relComidaController = new RelatorioComidaController(new RelatorioComidaView());
        relComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioComidaView2ActionPerformed

    private void miCalcImpacView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcImpacView2ActionPerformed
        ImpactoCalcularController impacCalcController = new ImpactoCalcularController(new ImpactoCalcularView());
        impacCalcController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcImpacView2ActionPerformed

    private void miVisualizarImpactoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarImpactoView2ActionPerformed
        ImpactoVisualizarController impacVisuController = new ImpactoVisualizarController(new ImpactoVisualizarView());
        impacVisuController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarImpactoView2ActionPerformed

    private void miCalcularDietaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDietaView2ActionPerformed
        DietaCalcularController dietaCalcularController = new DietaCalcularController(new DietaCalcularView());
        dietaCalcularController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcularDietaView2ActionPerformed

    private void miVisualizarDietaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarDietaView2ActionPerformed
        DietaVisualizarController dietaVisualizarController = new DietaVisualizarController(new DietaVisualizarView());
        dietaVisualizarController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarDietaView2ActionPerformed

    private void miCalcularDieta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDieta4ActionPerformed
        //Nada
    }//GEN-LAST:event_miCalcularDieta4ActionPerformed

    private void miRankingGeralView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRankingGeralView2ActionPerformed
        RankingGeralController rankingGeralController = new RankingGeralController(new RankingGeralView());
        rankingGeralController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRankingGeralView2ActionPerformed

    private void miRemPesView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemPesView1ActionPerformed
        RemoverPessoaController removerPessoaController = new RemoverPessoaController(new RemoverPessoaView());
        removerPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemPesView1ActionPerformed

    private void miRemRefeicaoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemRefeicaoView2ActionPerformed
        RefeicaoRemoverController refRemController = new RefeicaoRemoverController(new RefeicaoRemoverView());
        refRemController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemRefeicaoView2ActionPerformed

      
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadastroComida8;
    private javax.swing.JMenuItem btnCadastroPessoa5;
    private javax.swing.JMenu btnRefeicao8;
    private javax.swing.JMenuItem btnRefeicaoHistoricoView2;
    private javax.swing.JMenuItem btnRelatorioComidaView2;
    private javax.swing.JMenuItem btnRelatorioPessoasView2;
    private javax.swing.JMenu btnRelatório8;
    private javax.swing.JButton btnSalvarCadastroComida;
    private javax.swing.JComboBox<String> cmbDetalheCarne;
    private javax.swing.JComboBox<String> cmbTipoComida;
    private javax.swing.JComboBox<Pessoa> cmbTipoPessoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem miCalcImpacView2;
    private javax.swing.JMenu miCalcularDieta4;
    private javax.swing.JMenuItem miCalcularDietaView2;
    private javax.swing.JMenu miCalcularImpacto3;
    private javax.swing.JMenu miRankingGeral5;
    private javax.swing.JMenuItem miRankingGeralView2;
    private javax.swing.JMenuItem miRefNovaView2;
    private javax.swing.JMenuItem miRemPesView1;
    private javax.swing.JMenuItem miRemRefeicaoView2;
    private javax.swing.JMenuItem miVisualizarDietaView2;
    private javax.swing.JMenuItem miVisualizarImpactoView2;
    private javax.swing.JMenu mnCadastro8;
    private javax.swing.JMenu mnRemPesView1;
    private javax.swing.JTextField tfNomeComida;
    private javax.swing.JTextField tfrelComidaAgua;
    // End of variables declaration//GEN-END:variables
}
