/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import DAO.RefeicaoDAO;
import Model.Pessoa;
import Model.Refeicao;
import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author Usuário
 */
public class RefeicaoRemoverView extends javax.swing.JFrame {
    
    private RefeicaoDAO refeicaoDAO = new RefeicaoDAO();
    
    /**
     * Creates new form RefeicaoRemoverView
     */
    public RefeicaoRemoverView() {
        initComponents();
        Color backGroundColor=  new Color(221,221,221);
        this.getContentPane().setBackground(backGroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbRefRem = new javax.swing.JComboBox<>();
        cmbPesRemRef = new javax.swing.JComboBox<>();
        btnRemoverRefeicao = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro7 = new javax.swing.JMenu();
        btnCadastroPessoa4 = new javax.swing.JMenuItem();
        btnCadastroComida7 = new javax.swing.JMenuItem();
        btnRefeicao7 = new javax.swing.JMenu();
        miRefNovaView1 = new javax.swing.JMenuItem();
        btnRefeicaoHistoricoView1 = new javax.swing.JMenuItem();
        btnRelatório7 = new javax.swing.JMenu();
        btnRelatorioPessoasView1 = new javax.swing.JMenuItem();
        btnRelatorioComidaView1 = new javax.swing.JMenuItem();
        miCalcularImpacto2 = new javax.swing.JMenu();
        miCalcImpacView1 = new javax.swing.JMenuItem();
        miVisualizarImpactoView1 = new javax.swing.JMenuItem();
        miCalcularDieta5 = new javax.swing.JMenu();
        miCalcularDietaView1 = new javax.swing.JMenuItem();
        miVisualizarDietaView1 = new javax.swing.JMenuItem();
        miRankingGeral4 = new javax.swing.JMenu();
        miRankingGeralView2 = new javax.swing.JMenuItem();
        mnRemPesView1 = new javax.swing.JMenu();
        miRemPesView1 = new javax.swing.JMenuItem();
        miRemRefeicaoView1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Remover Refeição");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel3.setText("Pessoa:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jLabel4.setText("Refeição:");

        cmbRefRem.setBackground(new java.awt.Color(37, 201, 228));
        cmbRefRem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRefRemActionPerformed(evt);
            }
        });

        cmbPesRemRef.setBackground(new java.awt.Color(37, 201, 228));
        cmbPesRemRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbPesRemRefActionPerformed(evt);
            }
        });

        btnRemoverRefeicao.setText("Remover Refeição");
        btnRemoverRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverRefeicaoActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(42, 187, 242));

        mnCadastro7.setText("Cadastro");
        mnCadastro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastro7ActionPerformed(evt);
            }
        });

        btnCadastroPessoa4.setText("Cadastro Pessoa");
        btnCadastroPessoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoa4ActionPerformed(evt);
            }
        });
        mnCadastro7.add(btnCadastroPessoa4);

        btnCadastroComida7.setText("Cadastro Comida");
        btnCadastroComida7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroComida7ActionPerformed(evt);
            }
        });
        mnCadastro7.add(btnCadastroComida7);

        jMenuBar1.add(mnCadastro7);

        btnRefeicao7.setText("Refeição");
        btnRefeicao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicao7ActionPerformed(evt);
            }
        });

        miRefNovaView1.setText("Nova Refeição");
        miRefNovaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRefNovaView1ActionPerformed(evt);
            }
        });
        btnRefeicao7.add(miRefNovaView1);

        btnRefeicaoHistoricoView1.setText("Histórico Refeição");
        btnRefeicaoHistoricoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicaoHistoricoView1ActionPerformed(evt);
            }
        });
        btnRefeicao7.add(btnRefeicaoHistoricoView1);

        jMenuBar1.add(btnRefeicao7);

        btnRelatório7.setText("Relatório");

        btnRelatorioPessoasView1.setText("Pessoas");
        btnRelatorioPessoasView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPessoasView1ActionPerformed(evt);
            }
        });
        btnRelatório7.add(btnRelatorioPessoasView1);

        btnRelatorioComidaView1.setText("Comida");
        btnRelatorioComidaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioComidaView1ActionPerformed(evt);
            }
        });
        btnRelatório7.add(btnRelatorioComidaView1);

        jMenuBar1.add(btnRelatório7);

        miCalcularImpacto2.setText("Impacto");

        miCalcImpacView1.setText("Calcular Impacto");
        miCalcImpacView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcImpacView1ActionPerformed(evt);
            }
        });
        miCalcularImpacto2.add(miCalcImpacView1);

        miVisualizarImpactoView1.setText("Visualizar Impacto");
        miVisualizarImpactoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarImpactoView1ActionPerformed(evt);
            }
        });
        miCalcularImpacto2.add(miVisualizarImpactoView1);

        jMenuBar1.add(miCalcularImpacto2);

        miCalcularDieta5.setText("Dieta");
        miCalcularDieta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDieta5ActionPerformed(evt);
            }
        });

        miCalcularDietaView1.setText("Calcular Dieta");
        miCalcularDietaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDietaView1ActionPerformed(evt);
            }
        });
        miCalcularDieta5.add(miCalcularDietaView1);

        miVisualizarDietaView1.setText("Visualizar Dieta");
        miVisualizarDietaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarDietaView1ActionPerformed(evt);
            }
        });
        miCalcularDieta5.add(miVisualizarDietaView1);

        jMenuBar1.add(miCalcularDieta5);

        miRankingGeral4.setText("Ranking");

        miRankingGeralView2.setText("Ranking Geral");
        miRankingGeralView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRankingGeralView2ActionPerformed(evt);
            }
        });
        miRankingGeral4.add(miRankingGeralView2);

        jMenuBar1.add(miRankingGeral4);

        mnRemPesView1.setText("Remover");

        miRemPesView1.setText("Remover Pessoa");
        miRemPesView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemPesView1ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemPesView1);

        miRemRefeicaoView1.setText("Remover Refeição");
        miRemRefeicaoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemRefeicaoView1ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemRefeicaoView1);

        jMenuBar1.add(mnRemPesView1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbPesRemRef, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbRefRem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(6, 6, 6))
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addComponent(btnRemoverRefeicao)
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbPesRemRef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbRefRem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnRemoverRefeicao)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void exibirTela(){
        setVisible(true);
    }
    
    public void adicionarAcaoCMBPessoas(ActionListener acao){
        cmbPesRemRef.addActionListener(acao);
    }
    
    public void adicionarAcaoBotaoRemoverRef(ActionListener acao){
        btnRemoverRefeicao.addActionListener(acao);
    }
    
    public void adicionarAcaoCMBRefeicao(ActionListener acao){
        cmbRefRem.addActionListener(acao);
    }
    
    public int getContagem(){
        return cmbRefRem.getItemCount();
    }
    
    public Object getRefeicaoRemover(){
        return cmbRefRem.getSelectedItem();
    }
    
    public void removerAllItemsCMBPessoas(){
        cmbPesRemRef.removeAllItems();
    }
    
    public void removerAllItemsCMBRefeicoes(){
        cmbRefRem.removeAllItems();
    }
    
    public void addPessoaCMB(Pessoa p){
        cmbPesRemRef.addItem(p);
    }
    
    public Object getPessoaSelecionada(){
        return cmbPesRemRef.getSelectedItem();
    }
    
    public void addRefCMB(Refeicao r){
        cmbRefRem.addItem(r);
    }
    
    private void cmbPesRemRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbPesRemRefActionPerformed
        
    }//GEN-LAST:event_cmbPesRemRefActionPerformed
   
    private void btnRemoverRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverRefeicaoActionPerformed

        
    }//GEN-LAST:event_btnRemoverRefeicaoActionPerformed

    private void cmbRefRemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRefRemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRefRemActionPerformed

    private void miRefNovaView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRefNovaView3ActionPerformed
        RefeicaoNovaController refNovaController = new RefeicaoNovaController(new RefeicaoNovaView());
        refNovaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRefNovaView3ActionPerformed

    private void btnRefeicaoHistoricoView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicaoHistoricoView3ActionPerformed
        RefeicaoHistoricoController refHistController = new RefeicaoHistoricoController(new RefeicaoHistoricoView());
        refHistController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRefeicaoHistoricoView3ActionPerformed

    private void miRemRefeicaoView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemRefeicaoView3ActionPerformed
        RefeicaoRemoverController refRemController = new RefeicaoRemoverController(new RefeicaoRemoverView());
        refRemController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemRefeicaoView3ActionPerformed

    private void btnRelatorioPessoasView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPessoasView3ActionPerformed
        RelatorioPessoaController relComidaController = new RelatorioPessoaController(new RelatorioPessoaView());
        relComidaController.exibeTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioPessoasView3ActionPerformed

    private void btnRelatorioComidaView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioComidaView3ActionPerformed
        RelatorioComidaController relComidaController = new RelatorioComidaController(new RelatorioComidaView());
        relComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioComidaView3ActionPerformed

    private void miCalcImpacView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcImpacView3ActionPerformed
        ImpactoCalcularView impacCalcView = new ImpactoCalcularView();
        impacCalcView.show();
        dispose();
    }//GEN-LAST:event_miCalcImpacView3ActionPerformed

    private void miVisualizarImpactoView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarImpactoView3ActionPerformed
        ImpactoVisualizarView impacVisuView = new ImpactoVisualizarView();
        impacVisuView.show();
        dispose();
    }//GEN-LAST:event_miVisualizarImpactoView3ActionPerformed

    private void miCalcularDietaView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDietaView3ActionPerformed
        DietaCalcularView dietaCalcularView = new DietaCalcularView();
        dietaCalcularView.show();
        dispose();
    }//GEN-LAST:event_miCalcularDietaView3ActionPerformed

    private void miVisualizarDietaView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarDietaView3ActionPerformed
        DietaVisualizarView dietaVisualizarView = new DietaVisualizarView();
        dietaVisualizarView.show();
        dispose();
    }//GEN-LAST:event_miVisualizarDietaView3ActionPerformed

    private void btnCadastroPessoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoa4ActionPerformed
        CadastroPessoaController cadPessoaController = new CadastroPessoaController(new CadastroPessoaView());
        cadPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroPessoa4ActionPerformed

    private void btnCadastroComida7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroComida7ActionPerformed
        CadastroComidaController cadComidaController = new CadastroComidaController(new CadastroComidaView());
        cadComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroComida7ActionPerformed

    private void mnCadastro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastro7ActionPerformed
        //Nada
    }//GEN-LAST:event_mnCadastro7ActionPerformed

    private void miRefNovaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRefNovaView1ActionPerformed
        RefeicaoNovaController refNovaController = new RefeicaoNovaController(new RefeicaoNovaView());
        refNovaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRefNovaView1ActionPerformed

    private void btnRefeicaoHistoricoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicaoHistoricoView1ActionPerformed
        RefeicaoHistoricoController refHistController = new RefeicaoHistoricoController(new RefeicaoHistoricoView());
        refHistController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRefeicaoHistoricoView1ActionPerformed

    private void btnRefeicao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicao7ActionPerformed
        //Nada
    }//GEN-LAST:event_btnRefeicao7ActionPerformed

    private void btnRelatorioPessoasView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPessoasView1ActionPerformed
        RelatorioPessoaController relComidaController = new RelatorioPessoaController(new RelatorioPessoaView());
        relComidaController.exibeTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioPessoasView1ActionPerformed

    private void btnRelatorioComidaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioComidaView1ActionPerformed
        RelatorioComidaController relComidaController = new RelatorioComidaController(new RelatorioComidaView());
        relComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioComidaView1ActionPerformed

    private void miCalcImpacView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcImpacView1ActionPerformed
        ImpactoCalcularController impacCalcController = new ImpactoCalcularController(new ImpactoCalcularView());
        impacCalcController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcImpacView1ActionPerformed

    private void miVisualizarImpactoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarImpactoView1ActionPerformed
        ImpactoVisualizarController impacVisuController = new ImpactoVisualizarController(new ImpactoVisualizarView());
        impacVisuController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarImpactoView1ActionPerformed

    private void miCalcularDietaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDietaView1ActionPerformed
        DietaCalcularController dietaCalcularController = new DietaCalcularController(new DietaCalcularView());
        dietaCalcularController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcularDietaView1ActionPerformed

    private void miVisualizarDietaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarDietaView1ActionPerformed
        DietaVisualizarController dietaVisualizarController = new DietaVisualizarController(new DietaVisualizarView());
        dietaVisualizarController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarDietaView1ActionPerformed

    private void miCalcularDieta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDieta5ActionPerformed
        //Nada
    }//GEN-LAST:event_miCalcularDieta5ActionPerformed

    private void miRankingGeralView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRankingGeralView2ActionPerformed
        RankingGeralController rankingGeralController = new RankingGeralController(new RankingGeralView());
        rankingGeralController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRankingGeralView2ActionPerformed

    private void miRemPesView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemPesView1ActionPerformed
        RemoverPessoaController removerPessoaController = new RemoverPessoaController(new RemoverPessoaView());
        removerPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemPesView1ActionPerformed

    private void miRemRefeicaoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemRefeicaoView1ActionPerformed
        RefeicaoRemoverController refRemController = new RefeicaoRemoverController(new RefeicaoRemoverView());
        refRemController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemRefeicaoView1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadastroComida7;
    private javax.swing.JMenuItem btnCadastroPessoa4;
    private javax.swing.JMenu btnRefeicao7;
    private javax.swing.JMenuItem btnRefeicaoHistoricoView1;
    private javax.swing.JMenuItem btnRelatorioComidaView1;
    private javax.swing.JMenuItem btnRelatorioPessoasView1;
    private javax.swing.JMenu btnRelatório7;
    private javax.swing.JButton btnRemoverRefeicao;
    private javax.swing.JComboBox<Pessoa> cmbPesRemRef;
    private javax.swing.JComboBox<Refeicao> cmbRefRem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCalcImpacView1;
    private javax.swing.JMenu miCalcularDieta5;
    private javax.swing.JMenuItem miCalcularDietaView1;
    private javax.swing.JMenu miCalcularImpacto2;
    private javax.swing.JMenu miRankingGeral4;
    private javax.swing.JMenuItem miRankingGeralView2;
    private javax.swing.JMenuItem miRefNovaView1;
    private javax.swing.JMenuItem miRemPesView1;
    private javax.swing.JMenuItem miRemRefeicaoView1;
    private javax.swing.JMenuItem miVisualizarDietaView1;
    private javax.swing.JMenuItem miVisualizarImpactoView1;
    private javax.swing.JMenu mnCadastro7;
    private javax.swing.JMenu mnRemPesView1;
    // End of variables declaration//GEN-END:variables
}
