/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author Usuário
 */
public class RefeicaoHistoricoView extends javax.swing.JFrame {
    
    public RefeicaoHistoricoView() {
        initComponents();
        Color backGroundColor=  new Color(221,221,221);
        this.getContentPane().setBackground(backGroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        cmbRefHis = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRefHis = new javax.swing.JTextArea();
        btnVisualizarRefeicao = new javax.swing.JButton();
        btnLimparRefeicao = new javax.swing.JButton();
        rbUsuarioRefHis = new javax.swing.JRadioButton();
        rbDataRefHis = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnCadastro8 = new javax.swing.JMenu();
        btnCadastroPessoa5 = new javax.swing.JMenuItem();
        btnCadastroComida8 = new javax.swing.JMenuItem();
        btnRefeicao8 = new javax.swing.JMenu();
        miRefNovaView2 = new javax.swing.JMenuItem();
        btnRefeicaoHistoricoView2 = new javax.swing.JMenuItem();
        btnRelatório8 = new javax.swing.JMenu();
        btnRelatorioPessoasView2 = new javax.swing.JMenuItem();
        btnRelatorioComidaView2 = new javax.swing.JMenuItem();
        miCalcularImpacto3 = new javax.swing.JMenu();
        miCalcImpacView2 = new javax.swing.JMenuItem();
        miVisualizarImpactoView2 = new javax.swing.JMenuItem();
        miCalcularDieta4 = new javax.swing.JMenu();
        miCalcularDietaView2 = new javax.swing.JMenuItem();
        miVisualizarDietaView2 = new javax.swing.JMenuItem();
        miRankingGeral5 = new javax.swing.JMenu();
        miRankingGeralView1 = new javax.swing.JMenuItem();
        mnRemPesView1 = new javax.swing.JMenu();
        miRemPesView1 = new javax.swing.JMenuItem();
        miRemRefeicaoView2 = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cmbRefHis.setBackground(new java.awt.Color(37, 201, 228));
        cmbRefHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRefHisActionPerformed(evt);
            }
        });

        taRefHis.setColumns(20);
        taRefHis.setRows(5);
        jScrollPane1.setViewportView(taRefHis);

        btnVisualizarRefeicao.setText("Visualizar");
        btnVisualizarRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarRefeicaoActionPerformed(evt);
            }
        });

        btnLimparRefeicao.setText("Limpar");
        btnLimparRefeicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparRefeicaoActionPerformed(evt);
            }
        });

        rbUsuarioRefHis.setBackground(new java.awt.Color(221, 221, 221));
        rbUsuarioRefHis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbUsuarioRefHis.setText("Usuário");
        rbUsuarioRefHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbUsuarioRefHisActionPerformed(evt);
            }
        });

        rbDataRefHis.setBackground(new java.awt.Color(221, 221, 221));
        rbDataRefHis.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rbDataRefHis.setText("Data");
        rbDataRefHis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbDataRefHisActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Refeição Histórico");

        jMenuBar2.setBackground(new java.awt.Color(42, 187, 242));

        mnCadastro8.setText("Cadastro");
        mnCadastro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastro8ActionPerformed(evt);
            }
        });

        btnCadastroPessoa5.setText("Cadastro Pessoa");
        btnCadastroPessoa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoa5ActionPerformed(evt);
            }
        });
        mnCadastro8.add(btnCadastroPessoa5);

        btnCadastroComida8.setText("Cadastro Comida");
        btnCadastroComida8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroComida8ActionPerformed(evt);
            }
        });
        mnCadastro8.add(btnCadastroComida8);

        jMenuBar2.add(mnCadastro8);

        btnRefeicao8.setText("Refeição");
        btnRefeicao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicao8ActionPerformed(evt);
            }
        });

        miRefNovaView2.setText("Nova Refeição");
        miRefNovaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRefNovaView2ActionPerformed(evt);
            }
        });
        btnRefeicao8.add(miRefNovaView2);

        btnRefeicaoHistoricoView2.setText("Histórico Refeição");
        btnRefeicaoHistoricoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicaoHistoricoView2ActionPerformed(evt);
            }
        });
        btnRefeicao8.add(btnRefeicaoHistoricoView2);

        jMenuBar2.add(btnRefeicao8);

        btnRelatório8.setText("Relatório");

        btnRelatorioPessoasView2.setText("Pessoas");
        btnRelatorioPessoasView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPessoasView2ActionPerformed(evt);
            }
        });
        btnRelatório8.add(btnRelatorioPessoasView2);

        btnRelatorioComidaView2.setText("Comida");
        btnRelatorioComidaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioComidaView2ActionPerformed(evt);
            }
        });
        btnRelatório8.add(btnRelatorioComidaView2);

        jMenuBar2.add(btnRelatório8);

        miCalcularImpacto3.setText("Impacto");

        miCalcImpacView2.setText("Calcular Impacto");
        miCalcImpacView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcImpacView2ActionPerformed(evt);
            }
        });
        miCalcularImpacto3.add(miCalcImpacView2);

        miVisualizarImpactoView2.setText("Visualizar Impacto");
        miVisualizarImpactoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarImpactoView2ActionPerformed(evt);
            }
        });
        miCalcularImpacto3.add(miVisualizarImpactoView2);

        jMenuBar2.add(miCalcularImpacto3);

        miCalcularDieta4.setText("Dieta");
        miCalcularDieta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDieta4ActionPerformed(evt);
            }
        });

        miCalcularDietaView2.setText("Calcular Dieta");
        miCalcularDietaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDietaView2ActionPerformed(evt);
            }
        });
        miCalcularDieta4.add(miCalcularDietaView2);

        miVisualizarDietaView2.setText("Visualizar Dieta");
        miVisualizarDietaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarDietaView2ActionPerformed(evt);
            }
        });
        miCalcularDieta4.add(miVisualizarDietaView2);

        jMenuBar2.add(miCalcularDieta4);

        miRankingGeral5.setText("Ranking");

        miRankingGeralView1.setText("Ranking Geral");
        miRankingGeralView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRankingGeralView1ActionPerformed(evt);
            }
        });
        miRankingGeral5.add(miRankingGeralView1);

        jMenuBar2.add(miRankingGeral5);

        mnRemPesView1.setText("Remover");

        miRemPesView1.setText("Remover Pessoa");
        miRemPesView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemPesView1ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemPesView1);

        miRemRefeicaoView2.setText("Remover Refeição");
        miRemRefeicaoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemRefeicaoView2ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemRefeicaoView2);

        jMenuBar2.add(mnRemPesView1);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(163, 163, 163)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbRefHis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btnVisualizarRefeicao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLimparRefeicao))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(rbDataRefHis)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbUsuarioRefHis)
                        .addGap(128, 128, 128)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDataRefHis)
                    .addComponent(rbUsuarioRefHis))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbRefHis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizarRefeicao)
                    .addComponent(btnLimparRefeicao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//    private void popularComboBoxData(){
//        for(Refeicao r : refeicoes){
//            cmbDataRefeicao.addItem();//Fazer com que aparece somente a data e não o objeto como um todo
//        }
//    }

    private void btnLimparRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparRefeicaoActionPerformed
        
    }//GEN-LAST:event_btnLimparRefeicaoActionPerformed

    public void adicionarAcaoLimparRefHist(ActionListener acao){
        btnLimparRefeicao.addActionListener(acao);
    }
    
    public void adicionarAcaoVisualizarRefHist(ActionListener acao){
        btnVisualizarRefeicao.addActionListener(acao);
    }

    
    public void exibirTela(){
        setVisible(true);
    }
    
    public boolean getStateData(){
        return rbDataRefHis.isSelected();
    }
    
    public boolean getStateUsuario(){
        return rbUsuarioRefHis.isSelected();
    }
    
    public Object getRefeicao(){
        return cmbRefHis.getSelectedItem();
    }
    
    public void preencherTextAreaRefHist(String txt){
        taRefHis.append(txt);
    }
    
    public void limparTextAreaRefHist(){
        taRefHis.setText("");
    }
    
    public String StateTextAreaRefHist(){
        return taRefHis.getText();
    }    
        
    public void setEnableRBData(boolean state){
        rbDataRefHis.setEnabled(state);
    }
    
    public void adicionarAcaoRBDataRefHist(ActionListener acao){
        rbDataRefHis.addActionListener(acao);
    }
    
    public void adicionarAcaoRBUsuarioRefHist(ActionListener acao){
        rbUsuarioRefHis.addActionListener(acao);
    }
    
    public void removeAllItensCMBRefHist(){
        cmbRefHis.removeAllItems();
    }
    
    public void addItemCMBRefHist(String txt){
        cmbRefHis.addItem(txt);
    }
        
    public boolean stateRBUsuario(){
        return rbUsuarioRefHis.isSelected();
    }
    
    public void setEnableRBUsuario(boolean state){
        rbUsuarioRefHis.setEnabled(state);
    }
    
    private void rbDataRefHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDataRefHisActionPerformed
        
    }//GEN-LAST:event_rbDataRefHisActionPerformed

    private void cmbRefHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRefHisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbRefHisActionPerformed

    
    private void btnVisualizarRefeicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarRefeicaoActionPerformed
               
    }//GEN-LAST:event_btnVisualizarRefeicaoActionPerformed

    private void rbUsuarioRefHisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbUsuarioRefHisActionPerformed
        
    }//GEN-LAST:event_rbUsuarioRefHisActionPerformed

    private void btnCadastroPessoa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoa5ActionPerformed
        CadastroPessoaController cadPessoaController = new CadastroPessoaController(new CadastroPessoaView());
        cadPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroPessoa5ActionPerformed

    private void btnCadastroComida8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroComida8ActionPerformed
        CadastroComidaController cadComidaController = new CadastroComidaController(new CadastroComidaView());
        cadComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroComida8ActionPerformed

    private void mnCadastro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastro8ActionPerformed
        //Nada
    }//GEN-LAST:event_mnCadastro8ActionPerformed

    private void miRefNovaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRefNovaView2ActionPerformed
        RefeicaoNovaController refNovaController = new RefeicaoNovaController(new RefeicaoNovaView());
        refNovaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRefNovaView2ActionPerformed

    private void btnRefeicaoHistoricoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicaoHistoricoView2ActionPerformed
        RefeicaoHistoricoController refHistController = new RefeicaoHistoricoController(new RefeicaoHistoricoView());
        refHistController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRefeicaoHistoricoView2ActionPerformed

    private void btnRefeicao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicao8ActionPerformed
        //Nada
    }//GEN-LAST:event_btnRefeicao8ActionPerformed

    private void btnRelatorioPessoasView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPessoasView2ActionPerformed
        RelatorioPessoaController relComidaController = new RelatorioPessoaController(new RelatorioPessoaView());
        relComidaController.exibeTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioPessoasView2ActionPerformed

    private void btnRelatorioComidaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioComidaView2ActionPerformed
        RelatorioComidaController relComidaController = new RelatorioComidaController(new RelatorioComidaView());
        relComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioComidaView2ActionPerformed

    private void miCalcImpacView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcImpacView2ActionPerformed
        ImpactoCalcularController impacCalcController = new ImpactoCalcularController(new ImpactoCalcularView());
        impacCalcController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcImpacView2ActionPerformed

    private void miVisualizarImpactoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarImpactoView2ActionPerformed
        ImpactoVisualizarController impacVisuController = new ImpactoVisualizarController(new ImpactoVisualizarView());
        impacVisuController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarImpactoView2ActionPerformed

    private void miCalcularDietaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDietaView2ActionPerformed
        DietaCalcularController dietaCalcularController = new DietaCalcularController(new DietaCalcularView());
        dietaCalcularController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcularDietaView2ActionPerformed

    private void miVisualizarDietaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarDietaView2ActionPerformed
        DietaVisualizarController dietaVisualizarController = new DietaVisualizarController(new DietaVisualizarView());
        dietaVisualizarController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarDietaView2ActionPerformed

    private void miCalcularDieta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDieta4ActionPerformed
        //Nada
    }//GEN-LAST:event_miCalcularDieta4ActionPerformed

    private void miRankingGeralView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRankingGeralView1ActionPerformed
        RankingGeralController rankingGeralController = new RankingGeralController(new RankingGeralView());
        rankingGeralController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRankingGeralView1ActionPerformed

    private void miRemPesView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemPesView1ActionPerformed
        RemoverPessoaController removerPessoaController = new RemoverPessoaController(new RemoverPessoaView());
        removerPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemPesView1ActionPerformed

    private void miRemRefeicaoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemRefeicaoView2ActionPerformed
        RefeicaoRemoverController refRemController = new RefeicaoRemoverController(new RefeicaoRemoverView());
        refRemController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemRefeicaoView2ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadastroComida8;
    private javax.swing.JMenuItem btnCadastroPessoa5;
    private javax.swing.JButton btnLimparRefeicao;
    private javax.swing.JMenu btnRefeicao8;
    private javax.swing.JMenuItem btnRefeicaoHistoricoView2;
    private javax.swing.JMenuItem btnRelatorioComidaView2;
    private javax.swing.JMenuItem btnRelatorioPessoasView2;
    private javax.swing.JMenu btnRelatório8;
    private javax.swing.JButton btnVisualizarRefeicao;
    private javax.swing.JComboBox<String> cmbRefHis;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miCalcImpacView2;
    private javax.swing.JMenu miCalcularDieta4;
    private javax.swing.JMenuItem miCalcularDietaView2;
    private javax.swing.JMenu miCalcularImpacto3;
    private javax.swing.JMenu miRankingGeral5;
    private javax.swing.JMenuItem miRankingGeralView1;
    private javax.swing.JMenuItem miRefNovaView2;
    private javax.swing.JMenuItem miRemPesView1;
    private javax.swing.JMenuItem miRemRefeicaoView2;
    private javax.swing.JMenuItem miVisualizarDietaView2;
    private javax.swing.JMenuItem miVisualizarImpactoView2;
    private javax.swing.JMenu mnCadastro8;
    private javax.swing.JMenu mnRemPesView1;
    private javax.swing.JRadioButton rbDataRefHis;
    private javax.swing.JRadioButton rbUsuarioRefHis;
    private javax.swing.JTextArea taRefHis;
    // End of variables declaration//GEN-END:variables
}
