/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.Carne;
import Model.Comida;
import Model.Grao;
import Model.Pessoa;
import Model.Vegetal;
import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author Usuário
 */
public class RefeicaoNovaView extends javax.swing.JFrame {
    
    public RefeicaoNovaView(){
        initComponents();
        Color backGroundColor=  new Color(221,221,221);
        this.getContentPane().setBackground(backGroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel15 = new javax.swing.JLabel();
        txtDataRefeicaoNova = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtNomeRefeicaoNova = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnSalvarRefeicaoNova = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbCarnes = new javax.swing.JComboBox<>();
        cmbGraos = new javax.swing.JComboBox<>();
        cmbVegetais = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        txtPesoCarneRefeicaoNova = new javax.swing.JTextField();
        txtPesoGraoRefeicaoNova = new javax.swing.JTextField();
        txtPesoVegetalRefeicaoNova = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        cmbUsuarioRefeicaoNova = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro8 = new javax.swing.JMenu();
        btnCadastroPessoa5 = new javax.swing.JMenuItem();
        btnCadastroComida8 = new javax.swing.JMenuItem();
        btnRefeicao8 = new javax.swing.JMenu();
        miRefNovaView2 = new javax.swing.JMenuItem();
        btnRefeicaoHistoricoView2 = new javax.swing.JMenuItem();
        btnRelatório8 = new javax.swing.JMenu();
        btnRelatorioPessoasView2 = new javax.swing.JMenuItem();
        btnRelatorioComidaView2 = new javax.swing.JMenuItem();
        miCalcularImpacto2 = new javax.swing.JMenu();
        miCalcImpacView2 = new javax.swing.JMenuItem();
        miVisualizarImpactoView2 = new javax.swing.JMenuItem();
        miCalcularDieta5 = new javax.swing.JMenu();
        miCalcularDietaView2 = new javax.swing.JMenuItem();
        miVisualizarDietaView2 = new javax.swing.JMenuItem();
        miRankingGeral5 = new javax.swing.JMenu();
        miRankingGeralView2 = new javax.swing.JMenuItem();
        mnRemPesView1 = new javax.swing.JMenu();
        miRemPesView1 = new javax.swing.JMenuItem();
        miRemRefeicaoView2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Data:");

        txtDataRefeicaoNova.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDataRefeicaoNovaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDataRefeicaoNovaFocusLost(evt);
            }
        });
        txtDataRefeicaoNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataRefeicaoNovaActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Nome:");

        txtNomeRefeicaoNova.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNomeRefeicaoNovaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNomeRefeicaoNovaFocusLost(evt);
            }
        });
        txtNomeRefeicaoNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeRefeicaoNovaActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Carnes:");

        btnSalvarRefeicaoNova.setText("Salvar");
        btnSalvarRefeicaoNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarRefeicaoNovaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Grãos:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Vegetais:");

        cmbCarnes.setBackground(new java.awt.Color(37, 201, 228));
        cmbCarnes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCarnesActionPerformed(evt);
            }
        });

        cmbGraos.setBackground(new java.awt.Color(37, 201, 228));
        cmbGraos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGraosActionPerformed(evt);
            }
        });

        cmbVegetais.setBackground(new java.awt.Color(37, 201, 228));
        cmbVegetais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbVegetaisActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Peso:");

        txtPesoCarneRefeicaoNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoCarneRefeicaoNovaActionPerformed(evt);
            }
        });

        txtPesoGraoRefeicaoNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoGraoRefeicaoNovaActionPerformed(evt);
            }
        });

        txtPesoVegetalRefeicaoNova.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPesoVegetalRefeicaoNovaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Peso:");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("Peso:");

        jLabel6.setText("g");

        jLabel7.setText("g");

        jLabel10.setText("g");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Nova Refeição");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Pessoa:");
        jLabel11.setPreferredSize(new java.awt.Dimension(45, 20));

        cmbUsuarioRefeicaoNova.setBackground(new java.awt.Color(37, 201, 228));

        jMenuBar1.setBackground(new java.awt.Color(42, 187, 242));

        mnCadastro8.setText("Cadastro");
        mnCadastro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastro8ActionPerformed(evt);
            }
        });

        btnCadastroPessoa5.setText("Cadastro Pessoa");
        btnCadastroPessoa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoa5ActionPerformed(evt);
            }
        });
        mnCadastro8.add(btnCadastroPessoa5);

        btnCadastroComida8.setText("Cadastro Comida");
        btnCadastroComida8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroComida8ActionPerformed(evt);
            }
        });
        mnCadastro8.add(btnCadastroComida8);

        jMenuBar1.add(mnCadastro8);

        btnRefeicao8.setText("Refeição");
        btnRefeicao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicao8ActionPerformed(evt);
            }
        });

        miRefNovaView2.setText("Nova Refeição");
        miRefNovaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRefNovaView2ActionPerformed(evt);
            }
        });
        btnRefeicao8.add(miRefNovaView2);

        btnRefeicaoHistoricoView2.setText("Histórico Refeição");
        btnRefeicaoHistoricoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicaoHistoricoView2ActionPerformed(evt);
            }
        });
        btnRefeicao8.add(btnRefeicaoHistoricoView2);

        jMenuBar1.add(btnRefeicao8);

        btnRelatório8.setText("Relatório");

        btnRelatorioPessoasView2.setText("Pessoas");
        btnRelatorioPessoasView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPessoasView2ActionPerformed(evt);
            }
        });
        btnRelatório8.add(btnRelatorioPessoasView2);

        btnRelatorioComidaView2.setText("Comida");
        btnRelatorioComidaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioComidaView2ActionPerformed(evt);
            }
        });
        btnRelatório8.add(btnRelatorioComidaView2);

        jMenuBar1.add(btnRelatório8);

        miCalcularImpacto2.setText("Impacto");

        miCalcImpacView2.setText("Calcular Impacto");
        miCalcImpacView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcImpacView2ActionPerformed(evt);
            }
        });
        miCalcularImpacto2.add(miCalcImpacView2);

        miVisualizarImpactoView2.setText("Visualizar Impacto");
        miVisualizarImpactoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarImpactoView2ActionPerformed(evt);
            }
        });
        miCalcularImpacto2.add(miVisualizarImpactoView2);

        jMenuBar1.add(miCalcularImpacto2);

        miCalcularDieta5.setText("Dieta");
        miCalcularDieta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDieta5ActionPerformed(evt);
            }
        });

        miCalcularDietaView2.setText("Calcular Dieta");
        miCalcularDietaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDietaView2ActionPerformed(evt);
            }
        });
        miCalcularDieta5.add(miCalcularDietaView2);

        miVisualizarDietaView2.setText("Visualizar Dieta");
        miVisualizarDietaView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarDietaView2ActionPerformed(evt);
            }
        });
        miCalcularDieta5.add(miVisualizarDietaView2);

        jMenuBar1.add(miCalcularDieta5);

        miRankingGeral5.setText("Ranking");

        miRankingGeralView2.setText("Ranking Geral");
        miRankingGeralView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRankingGeralView2ActionPerformed(evt);
            }
        });
        miRankingGeral5.add(miRankingGeralView2);

        jMenuBar1.add(miRankingGeral5);

        mnRemPesView1.setText("Remover");

        miRemPesView1.setText("Remover Pessoa");
        miRemPesView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemPesView1ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemPesView1);

        miRemRefeicaoView2.setText("Remover Refeição");
        miRemRefeicaoView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemRefeicaoView2ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemRefeicaoView2);

        jMenuBar1.add(mnRemPesView1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(311, 311, 311))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbUsuarioRefeicaoNova, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNomeRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtDataRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(105, 105, 105))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmbVegetais, 0, 429, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(25, 25, 25)
                                        .addComponent(cmbGraos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbCarnes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPesoCarneRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPesoGraoRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtPesoVegetalRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel7)))
                                .addGap(86, 86, 86))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnSalvarRefeicaoNova)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtDataRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbUsuarioRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(txtNomeRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbCarnes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtPesoCarneRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cmbGraos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoGraoRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbVegetais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesoVegetalRefeicaoNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addComponent(btnSalvarRefeicaoNova)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void txtDataRefeicaoNovaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataRefeicaoNovaFocusGained

    }//GEN-LAST:event_txtDataRefeicaoNovaFocusGained

    private void txtDataRefeicaoNovaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDataRefeicaoNovaFocusLost

    }//GEN-LAST:event_txtDataRefeicaoNovaFocusLost

    private void txtDataRefeicaoNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataRefeicaoNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataRefeicaoNovaActionPerformed

    private void txtNomeRefeicaoNovaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeRefeicaoNovaFocusGained

    }//GEN-LAST:event_txtNomeRefeicaoNovaFocusGained

    private void txtNomeRefeicaoNovaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNomeRefeicaoNovaFocusLost

    }//GEN-LAST:event_txtNomeRefeicaoNovaFocusLost

    private void txtNomeRefeicaoNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeRefeicaoNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeRefeicaoNovaActionPerformed
    
    public void adicionarAcaoBotaoRefNova(ActionListener acao){
        btnSalvarRefeicaoNova.addActionListener(acao);
    }
    
    public void exibirTela(){
        setVisible(true);
    }
    
    public String getDataRefNova(){
        return txtDataRefeicaoNova.getText();
    }
    
    public String getNomeRefNova(){
        return txtNomeRefeicaoNova.getText();
    }
    
    public Object getUserRefNova(){     
        Object userRefNova = cmbUsuarioRefeicaoNova.getSelectedItem();        
        return userRefNova;
    }
    
    public Object getTipoCarneRefNova(){  
        Object tipoCarneRefNova = cmbCarnes.getSelectedItem();        
        return tipoCarneRefNova;
    }
    
    public String getPesoTipoCarne(){
        return txtPesoCarneRefeicaoNova.getText();
    }
    
    public Object getTipoGraoRefNova(){ 
        Object tipoGraoRefNova = cmbGraos.getSelectedItem();        
        return tipoGraoRefNova;
    }
    
    public String getPesoTipoGrao(){
        return txtPesoGraoRefeicaoNova.getText();
    }
    
    public Object getTipoVegetalRefNova(){     
        Object tipoVegetalRefNova = cmbVegetais.getSelectedItem();        
        return tipoVegetalRefNova;
    }
    
    public String getPesoTipoVegetal(){
        return txtPesoVegetalRefeicaoNova.getText();
    }
    
//    public void populaarComboBoxes(){
//        Collections.sort(comidas);
//        for(Comida c : comidas){
//            if(c.getTipoComida().equals("Carne")){
//                addCMBCarne(c);
//            }
//            if(c.getTipoComida().equals("Grão")){
//                addCMBGrao(c);
//            }
//            if(c.getTipoComida().equals("Vegetal")){
//                addCMBVegetal(c);
//            }
//        }   
//    }
    
    public void addCMBCarne(Comida c){
        cmbCarnes.addItem((Carne) c);
    }
    
    public void addCMBGrao(Comida c){
        cmbGraos.addItem((Grao) c);
    }
    
    public void addCMBVegetal(Comida c){
        cmbVegetais.addItem((Vegetal) c);
    }
    
    public void addCMBPessoa(Pessoa p){
        cmbUsuarioRefeicaoNova.addItem(p);
    }
    
    private void btnSalvarRefeicaoNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarRefeicaoNovaActionPerformed
       
    }//GEN-LAST:event_btnSalvarRefeicaoNovaActionPerformed

    private void cmbCarnesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCarnesActionPerformed
               
    }//GEN-LAST:event_cmbCarnesActionPerformed

    private void cmbGraosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGraosActionPerformed
        
    }//GEN-LAST:event_cmbGraosActionPerformed

    private void cmbVegetaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbVegetaisActionPerformed
        
    }//GEN-LAST:event_cmbVegetaisActionPerformed

    private void txtPesoCarneRefeicaoNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoCarneRefeicaoNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoCarneRefeicaoNovaActionPerformed

    private void txtPesoGraoRefeicaoNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoGraoRefeicaoNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoGraoRefeicaoNovaActionPerformed

    private void txtPesoVegetalRefeicaoNovaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPesoVegetalRefeicaoNovaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesoVegetalRefeicaoNovaActionPerformed

    private void btnCadastroPessoa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoa5ActionPerformed
        CadastroPessoaController cadPessoaController = new CadastroPessoaController(new CadastroPessoaView());
        cadPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroPessoa5ActionPerformed

    private void btnCadastroComida8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroComida8ActionPerformed
        CadastroComidaController cadComidaController = new CadastroComidaController(new CadastroComidaView());
        cadComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroComida8ActionPerformed

    private void mnCadastro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastro8ActionPerformed
        //Nada
    }//GEN-LAST:event_mnCadastro8ActionPerformed

    private void miRefNovaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRefNovaView2ActionPerformed
        RefeicaoNovaController refNovaController = new RefeicaoNovaController(new RefeicaoNovaView());
        refNovaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRefNovaView2ActionPerformed

    private void btnRefeicaoHistoricoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicaoHistoricoView2ActionPerformed
        RefeicaoHistoricoController refHistController = new RefeicaoHistoricoController(new RefeicaoHistoricoView());
        refHistController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRefeicaoHistoricoView2ActionPerformed

    private void btnRefeicao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicao8ActionPerformed
        //Nada
    }//GEN-LAST:event_btnRefeicao8ActionPerformed

    private void btnRelatorioPessoasView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPessoasView2ActionPerformed
        RelatorioPessoaController relComidaController = new RelatorioPessoaController(new RelatorioPessoaView());
        relComidaController.exibeTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioPessoasView2ActionPerformed

    private void btnRelatorioComidaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioComidaView2ActionPerformed
        RelatorioComidaController relComidaController = new RelatorioComidaController(new RelatorioComidaView());
        relComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioComidaView2ActionPerformed

    private void miCalcImpacView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcImpacView2ActionPerformed
        ImpactoCalcularController impacCalcController = new ImpactoCalcularController(new ImpactoCalcularView());
        impacCalcController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcImpacView2ActionPerformed

    private void miVisualizarImpactoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarImpactoView2ActionPerformed
        ImpactoVisualizarController impacVisuController = new ImpactoVisualizarController(new ImpactoVisualizarView());
        impacVisuController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarImpactoView2ActionPerformed

    private void miCalcularDietaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDietaView2ActionPerformed
        DietaCalcularController dietaCalcularController = new DietaCalcularController(new DietaCalcularView());
        dietaCalcularController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcularDietaView2ActionPerformed

    private void miVisualizarDietaView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarDietaView2ActionPerformed
        DietaVisualizarController dietaVisualizarController = new DietaVisualizarController(new DietaVisualizarView());
        dietaVisualizarController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarDietaView2ActionPerformed

    private void miCalcularDieta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDieta5ActionPerformed
        //Nada
    }//GEN-LAST:event_miCalcularDieta5ActionPerformed

    private void miRankingGeralView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRankingGeralView2ActionPerformed
        RankingGeralController rankingGeralController = new RankingGeralController(new RankingGeralView());
        rankingGeralController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRankingGeralView2ActionPerformed

    private void miRemPesView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemPesView1ActionPerformed
        RemoverPessoaController removerPessoaController = new RemoverPessoaController(new RemoverPessoaView());
        removerPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemPesView1ActionPerformed

    private void miRemRefeicaoView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemRefeicaoView2ActionPerformed
        RefeicaoRemoverController refRemController = new RefeicaoRemoverController(new RefeicaoRemoverView());
        refRemController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemRefeicaoView2ActionPerformed

   
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadastroComida8;
    private javax.swing.JMenuItem btnCadastroPessoa5;
    private javax.swing.JMenu btnRefeicao8;
    private javax.swing.JMenuItem btnRefeicaoHistoricoView2;
    private javax.swing.JMenuItem btnRelatorioComidaView2;
    private javax.swing.JMenuItem btnRelatorioPessoasView2;
    private javax.swing.JMenu btnRelatório8;
    private javax.swing.JButton btnSalvarRefeicaoNova;
    private javax.swing.JComboBox<Carne> cmbCarnes;
    private javax.swing.JComboBox<Grao> cmbGraos;
    private javax.swing.JComboBox<Pessoa> cmbUsuarioRefeicaoNova;
    private javax.swing.JComboBox<Vegetal> cmbVegetais;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCalcImpacView2;
    private javax.swing.JMenu miCalcularDieta5;
    private javax.swing.JMenuItem miCalcularDietaView2;
    private javax.swing.JMenu miCalcularImpacto2;
    private javax.swing.JMenu miRankingGeral5;
    private javax.swing.JMenuItem miRankingGeralView2;
    private javax.swing.JMenuItem miRefNovaView2;
    private javax.swing.JMenuItem miRemPesView1;
    private javax.swing.JMenuItem miRemRefeicaoView2;
    private javax.swing.JMenuItem miVisualizarDietaView2;
    private javax.swing.JMenuItem miVisualizarImpactoView2;
    private javax.swing.JMenu mnCadastro8;
    private javax.swing.JMenu mnRemPesView1;
    private javax.swing.JTextField txtDataRefeicaoNova;
    private javax.swing.JTextField txtNomeRefeicaoNova;
    private javax.swing.JTextField txtPesoCarneRefeicaoNova;
    private javax.swing.JTextField txtPesoGraoRefeicaoNova;
    private javax.swing.JTextField txtPesoVegetalRefeicaoNova;
    // End of variables declaration//GEN-END:variables
}
