/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import java.awt.Color;
import java.awt.event.ActionListener;

/**
 *
 * @author Usuário
 */
public class RelatorioComidaView extends javax.swing.JFrame {

    /**
     * Creates new form ExemploMenu
     */
    public RelatorioComidaView() {
        initComponents();
        Color backGroundColor=  new Color(221,221,221);
        this.getContentPane().setBackground(backGroundColor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        taRelCom = new javax.swing.JTextArea();
        btnRelatorioLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cmbRelCom = new javax.swing.JComboBox<>();
        btnRetComOrd = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro8 = new javax.swing.JMenu();
        btnCadastroPessoa5 = new javax.swing.JMenuItem();
        btnCadastroComida8 = new javax.swing.JMenuItem();
        btnRefeicao8 = new javax.swing.JMenu();
        miRefNovaView3 = new javax.swing.JMenuItem();
        btnRefeicaoHistoricoView3 = new javax.swing.JMenuItem();
        btnRelatório8 = new javax.swing.JMenu();
        btnRelatorioPessoasView3 = new javax.swing.JMenuItem();
        btnRelatorioComidaView3 = new javax.swing.JMenuItem();
        miCalcularImpacto3 = new javax.swing.JMenu();
        miCalcImpacView3 = new javax.swing.JMenuItem();
        miVisualizarImpactoView3 = new javax.swing.JMenuItem();
        miCalcularDieta6 = new javax.swing.JMenu();
        miCalcularDietaView3 = new javax.swing.JMenuItem();
        miVisualizarDietaView3 = new javax.swing.JMenuItem();
        miRankingGeral6 = new javax.swing.JMenu();
        miRankingGeralView3 = new javax.swing.JMenuItem();
        mnRemPesView3 = new javax.swing.JMenu();
        miRemPesView3 = new javax.swing.JMenuItem();
        miRemRefeicaoView4 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        taRelCom.setColumns(20);
        taRelCom.setRows(5);
        jScrollPane1.setViewportView(taRelCom);

        btnRelatorioLimpar.setText("Limpar");
        btnRelatorioLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioLimparActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Relatório Comidas");

        cmbRelCom.setBackground(new java.awt.Color(37, 201, 228));
        cmbRelCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Carnes", "Grãos", "Vegetais" }));
        cmbRelCom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbRelComActionPerformed(evt);
            }
        });

        btnRetComOrd.setText("Retornar Comidas Ordenadas");
        btnRetComOrd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetComOrdActionPerformed(evt);
            }
        });

        jMenuBar1.setBackground(new java.awt.Color(42, 187, 242));

        mnCadastro8.setText("Cadastro");
        mnCadastro8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastro8ActionPerformed(evt);
            }
        });

        btnCadastroPessoa5.setText("Cadastro Pessoa");
        btnCadastroPessoa5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoa5ActionPerformed(evt);
            }
        });
        mnCadastro8.add(btnCadastroPessoa5);

        btnCadastroComida8.setText("Cadastro Comida");
        btnCadastroComida8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroComida8ActionPerformed(evt);
            }
        });
        mnCadastro8.add(btnCadastroComida8);

        jMenuBar1.add(mnCadastro8);

        btnRefeicao8.setText("Refeição");
        btnRefeicao8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicao8ActionPerformed(evt);
            }
        });

        miRefNovaView3.setText("Nova Refeição");
        miRefNovaView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRefNovaView3ActionPerformed(evt);
            }
        });
        btnRefeicao8.add(miRefNovaView3);

        btnRefeicaoHistoricoView3.setText("Histórico Refeição");
        btnRefeicaoHistoricoView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicaoHistoricoView3ActionPerformed(evt);
            }
        });
        btnRefeicao8.add(btnRefeicaoHistoricoView3);

        jMenuBar1.add(btnRefeicao8);

        btnRelatório8.setText("Relatório");

        btnRelatorioPessoasView3.setText("Pessoas");
        btnRelatorioPessoasView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPessoasView3ActionPerformed(evt);
            }
        });
        btnRelatório8.add(btnRelatorioPessoasView3);

        btnRelatorioComidaView3.setText("Comida");
        btnRelatorioComidaView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioComidaView3ActionPerformed(evt);
            }
        });
        btnRelatório8.add(btnRelatorioComidaView3);

        jMenuBar1.add(btnRelatório8);

        miCalcularImpacto3.setText("Impacto");

        miCalcImpacView3.setText("Calcular Impacto");
        miCalcImpacView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcImpacView3ActionPerformed(evt);
            }
        });
        miCalcularImpacto3.add(miCalcImpacView3);

        miVisualizarImpactoView3.setText("Visualizar Impacto");
        miVisualizarImpactoView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarImpactoView3ActionPerformed(evt);
            }
        });
        miCalcularImpacto3.add(miVisualizarImpactoView3);

        jMenuBar1.add(miCalcularImpacto3);

        miCalcularDieta6.setText("Dieta");
        miCalcularDieta6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDieta6ActionPerformed(evt);
            }
        });

        miCalcularDietaView3.setText("Calcular Dieta");
        miCalcularDietaView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDietaView3ActionPerformed(evt);
            }
        });
        miCalcularDieta6.add(miCalcularDietaView3);

        miVisualizarDietaView3.setText("Visualizar Dieta");
        miVisualizarDietaView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarDietaView3ActionPerformed(evt);
            }
        });
        miCalcularDieta6.add(miVisualizarDietaView3);

        jMenuBar1.add(miCalcularDieta6);

        miRankingGeral6.setText("Ranking");

        miRankingGeralView3.setText("Ranking Geral");
        miRankingGeralView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRankingGeralView3ActionPerformed(evt);
            }
        });
        miRankingGeral6.add(miRankingGeralView3);

        jMenuBar1.add(miRankingGeral6);

        mnRemPesView3.setText("Remover");

        miRemPesView3.setText("Remover Pessoa");
        miRemPesView3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemPesView3ActionPerformed(evt);
            }
        });
        mnRemPesView3.add(miRemPesView3);

        miRemRefeicaoView4.setText("Remover Refeição");
        miRemRefeicaoView4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemRefeicaoView4ActionPerformed(evt);
            }
        });
        mnRemPesView3.add(miRemRefeicaoView4);

        jMenuBar1.add(mnRemPesView3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbRelCom, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRelatorioLimpar)
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRetComOrd)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)))
                .addContainerGap(169, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbRelCom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRelatorioLimpar)
                    .addComponent(btnRetComOrd))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void exibirTela(){
        setVisible(true);
    }
    
    public void limparTextArea(){
        taRelCom.setText("");
    }
    
    public String getTipoCarne(){
        return cmbRelCom.getSelectedItem().toString();
    }
    
    public void adicionarAcaoRetornarTodasRelatorioComida(ActionListener acao){
        btnRetComOrd.addActionListener(acao);
    }
    
    public void adicionarAcaoLimpar(ActionListener acao){
        btnRelatorioLimpar.addActionListener(acao);
    }
    
    public void adicionarAcaoCMBComidas(ActionListener acao){
        cmbRelCom.addActionListener(acao);
    }
    
    public void preencherTextArea(String txt){
        taRelCom.append(txt);
    }
    
    private void cmbRelComActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbRelComActionPerformed
        
    }//GEN-LAST:event_cmbRelComActionPerformed

    private void btnRelatorioLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioLimparActionPerformed

    }//GEN-LAST:event_btnRelatorioLimparActionPerformed

    private void btnRetComOrdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetComOrdActionPerformed
       
    }//GEN-LAST:event_btnRetComOrdActionPerformed

    private void btnCadastroPessoa5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoa5ActionPerformed
        CadastroPessoaController cadPessoaController = new CadastroPessoaController(new CadastroPessoaView());
        cadPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroPessoa5ActionPerformed

    private void btnCadastroComida8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroComida8ActionPerformed
        CadastroComidaController cadComidaController = new CadastroComidaController(new CadastroComidaView());
        cadComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroComida8ActionPerformed

    private void mnCadastro8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastro8ActionPerformed
        //Nada
    }//GEN-LAST:event_mnCadastro8ActionPerformed

    private void miRefNovaView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRefNovaView3ActionPerformed
        RefeicaoNovaController refNovaController = new RefeicaoNovaController(new RefeicaoNovaView());
        refNovaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRefNovaView3ActionPerformed

    private void btnRefeicaoHistoricoView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicaoHistoricoView3ActionPerformed
        RefeicaoHistoricoController refHistController = new RefeicaoHistoricoController(new RefeicaoHistoricoView());
        refHistController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRefeicaoHistoricoView3ActionPerformed

    private void btnRefeicao8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicao8ActionPerformed
        //Nada
    }//GEN-LAST:event_btnRefeicao8ActionPerformed

    private void btnRelatorioPessoasView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPessoasView3ActionPerformed
        RelatorioPessoaController relComidaController = new RelatorioPessoaController(new RelatorioPessoaView());
        relComidaController.exibeTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioPessoasView3ActionPerformed

    private void btnRelatorioComidaView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioComidaView3ActionPerformed
        RelatorioComidaController relComidaController = new RelatorioComidaController(new RelatorioComidaView());
        relComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioComidaView3ActionPerformed

    private void miCalcImpacView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcImpacView3ActionPerformed
        ImpactoCalcularController impacCalcController = new ImpactoCalcularController(new ImpactoCalcularView());
        impacCalcController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcImpacView3ActionPerformed

    private void miVisualizarImpactoView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarImpactoView3ActionPerformed
        ImpactoVisualizarController impacVisuController = new ImpactoVisualizarController(new ImpactoVisualizarView());
        impacVisuController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarImpactoView3ActionPerformed

    private void miCalcularDietaView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDietaView3ActionPerformed
        DietaCalcularController dietaCalcularController = new DietaCalcularController(new DietaCalcularView());
        dietaCalcularController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcularDietaView3ActionPerformed

    private void miVisualizarDietaView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarDietaView3ActionPerformed
        DietaVisualizarController dietaVisualizarController = new DietaVisualizarController(new DietaVisualizarView());
        dietaVisualizarController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarDietaView3ActionPerformed

    private void miCalcularDieta6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDieta6ActionPerformed
        //Nada
    }//GEN-LAST:event_miCalcularDieta6ActionPerformed

    private void miRankingGeralView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRankingGeralView3ActionPerformed
        RankingGeralController rankingGeralController = new RankingGeralController(new RankingGeralView());
        rankingGeralController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRankingGeralView3ActionPerformed

    private void miRemPesView3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemPesView3ActionPerformed
        RemoverPessoaController removerPessoaController = new RemoverPessoaController(new RemoverPessoaView());
        removerPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemPesView3ActionPerformed

    private void miRemRefeicaoView4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemRefeicaoView4ActionPerformed
        RefeicaoRemoverController refRemController = new RefeicaoRemoverController(new RefeicaoRemoverView());
        refRemController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemRefeicaoView4ActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadastroComida8;
    private javax.swing.JMenuItem btnCadastroPessoa5;
    private javax.swing.JMenu btnRefeicao8;
    private javax.swing.JMenuItem btnRefeicaoHistoricoView3;
    private javax.swing.JMenuItem btnRelatorioComidaView3;
    private javax.swing.JButton btnRelatorioLimpar;
    private javax.swing.JMenuItem btnRelatorioPessoasView3;
    private javax.swing.JMenu btnRelatório8;
    private javax.swing.JButton btnRetComOrd;
    private javax.swing.JComboBox<String> cmbRelCom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem miCalcImpacView3;
    private javax.swing.JMenu miCalcularDieta6;
    private javax.swing.JMenuItem miCalcularDietaView3;
    private javax.swing.JMenu miCalcularImpacto3;
    private javax.swing.JMenu miRankingGeral6;
    private javax.swing.JMenuItem miRankingGeralView3;
    private javax.swing.JMenuItem miRefNovaView3;
    private javax.swing.JMenuItem miRemPesView3;
    private javax.swing.JMenuItem miRemRefeicaoView4;
    private javax.swing.JMenuItem miVisualizarDietaView3;
    private javax.swing.JMenuItem miVisualizarImpactoView3;
    private javax.swing.JMenu mnCadastro8;
    private javax.swing.JMenu mnRemPesView3;
    private javax.swing.JTextArea taRelCom;
    // End of variables declaration//GEN-END:variables
}
