/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.*;
import Model.Pessoa;
import java.awt.event.ActionListener;
/**
 *
 * @author Gabriela
 */
public class RemoverPessoaView extends javax.swing.JFrame {

    /**
     * Creates new form RemoverPessoaView
     */
    public RemoverPessoaView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmbCategoriasRemPesVoew = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        tfRemPesView = new javax.swing.JTextField();
        btnBuscarRemPesView = new javax.swing.JButton();
        cmbPessoaRemPesView = new javax.swing.JComboBox<>();
        btnRemoverRemPesView = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnCadastro7 = new javax.swing.JMenu();
        btnCadastroPessoa4 = new javax.swing.JMenuItem();
        btnCadastroComida7 = new javax.swing.JMenuItem();
        btnRefeicao7 = new javax.swing.JMenu();
        miRefNovaView1 = new javax.swing.JMenuItem();
        btnRefeicaoHistoricoView1 = new javax.swing.JMenuItem();
        btnRelatório7 = new javax.swing.JMenu();
        btnRelatorioPessoasView1 = new javax.swing.JMenuItem();
        btnRelatorioComidaView1 = new javax.swing.JMenuItem();
        miCalcularImpacto2 = new javax.swing.JMenu();
        miCalcImpacView1 = new javax.swing.JMenuItem();
        miVisualizarImpactoView1 = new javax.swing.JMenuItem();
        miCalcularDieta4 = new javax.swing.JMenu();
        miCalcularDietaView1 = new javax.swing.JMenuItem();
        miVisualizarDietaView1 = new javax.swing.JMenuItem();
        miRankingGeral4 = new javax.swing.JMenu();
        miRankingGeralView1 = new javax.swing.JMenuItem();
        mnRemPesView = new javax.swing.JMenu();
        miRemPesView = new javax.swing.JMenuItem();
        miRemRefeicaoView1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Remover Pessoa");

        cmbCategoriasRemPesVoew.setBackground(new java.awt.Color(37, 201, 228));
        cmbCategoriasRemPesVoew.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Orientação Alimentar", "CPF", "Idade", "Tipo Pessoa" }));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Buscar:");

        btnBuscarRemPesView.setText("Buscar");

        cmbPessoaRemPesView.setBackground(new java.awt.Color(37, 201, 228));

        btnRemoverRemPesView.setText("Remover Pessoa");

        jMenuBar2.setBackground(new java.awt.Color(42, 187, 242));

        mnCadastro7.setText("Cadastro");
        mnCadastro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastro7ActionPerformed(evt);
            }
        });

        btnCadastroPessoa4.setText("Cadastro Pessoa");
        btnCadastroPessoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoa4ActionPerformed(evt);
            }
        });
        mnCadastro7.add(btnCadastroPessoa4);

        btnCadastroComida7.setText("Cadastro Comida");
        btnCadastroComida7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroComida7ActionPerformed(evt);
            }
        });
        mnCadastro7.add(btnCadastroComida7);

        jMenuBar2.add(mnCadastro7);

        btnRefeicao7.setText("Refeição");
        btnRefeicao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicao7ActionPerformed(evt);
            }
        });

        miRefNovaView1.setText("Nova Refeição");
        miRefNovaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRefNovaView1ActionPerformed(evt);
            }
        });
        btnRefeicao7.add(miRefNovaView1);

        btnRefeicaoHistoricoView1.setText("Histórico Refeição");
        btnRefeicaoHistoricoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicaoHistoricoView1ActionPerformed(evt);
            }
        });
        btnRefeicao7.add(btnRefeicaoHistoricoView1);

        jMenuBar2.add(btnRefeicao7);

        btnRelatório7.setText("Relatório");

        btnRelatorioPessoasView1.setText("Pessoas");
        btnRelatorioPessoasView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPessoasView1ActionPerformed(evt);
            }
        });
        btnRelatório7.add(btnRelatorioPessoasView1);

        btnRelatorioComidaView1.setText("Comida");
        btnRelatorioComidaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioComidaView1ActionPerformed(evt);
            }
        });
        btnRelatório7.add(btnRelatorioComidaView1);

        jMenuBar2.add(btnRelatório7);

        miCalcularImpacto2.setText("Impacto");

        miCalcImpacView1.setText("Calcular Impacto");
        miCalcImpacView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcImpacView1ActionPerformed(evt);
            }
        });
        miCalcularImpacto2.add(miCalcImpacView1);

        miVisualizarImpactoView1.setText("Visualizar Impacto");
        miVisualizarImpactoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarImpactoView1ActionPerformed(evt);
            }
        });
        miCalcularImpacto2.add(miVisualizarImpactoView1);

        jMenuBar2.add(miCalcularImpacto2);

        miCalcularDieta4.setText("Dieta");
        miCalcularDieta4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDieta4ActionPerformed(evt);
            }
        });

        miCalcularDietaView1.setText("Calcular Dieta");
        miCalcularDietaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDietaView1ActionPerformed(evt);
            }
        });
        miCalcularDieta4.add(miCalcularDietaView1);

        miVisualizarDietaView1.setText("Visualizar Dieta");
        miVisualizarDietaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarDietaView1ActionPerformed(evt);
            }
        });
        miCalcularDieta4.add(miVisualizarDietaView1);

        jMenuBar2.add(miCalcularDieta4);

        miRankingGeral4.setText("Ranking");

        miRankingGeralView1.setText("Ranking Geral");
        miRankingGeralView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRankingGeralView1ActionPerformed(evt);
            }
        });
        miRankingGeral4.add(miRankingGeralView1);

        jMenuBar2.add(miRankingGeral4);

        mnRemPesView.setText("Remover");

        miRemPesView.setText("Remover Pessoa");
        miRemPesView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemPesViewActionPerformed(evt);
            }
        });
        mnRemPesView.add(miRemPesView);

        miRemRefeicaoView1.setText("Remover Refeição");
        miRemRefeicaoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemRefeicaoView1ActionPerformed(evt);
            }
        });
        mnRemPesView.add(miRemRefeicaoView1);

        jMenuBar2.add(mnRemPesView);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbPessoaRemPesView, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfRemPesView)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnBuscarRemPesView))
                            .addComponent(cmbCategoriasRemPesVoew, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 150, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(135, 135, 135))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRemoverRemPesView)
                .addGap(147, 147, 147))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(cmbCategoriasRemPesVoew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfRemPesView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarRemPesView))
                .addGap(31, 31, 31)
                .addComponent(cmbPessoaRemPesView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnRemoverRemPesView)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroPessoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoa4ActionPerformed
        CadastroPessoaController cadPessoaController = new CadastroPessoaController(new CadastroPessoaView());
        cadPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroPessoa4ActionPerformed

    private void btnCadastroComida7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroComida7ActionPerformed
        CadastroComidaController cadComidaController = new CadastroComidaController(new CadastroComidaView());
        cadComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroComida7ActionPerformed

    private void mnCadastro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastro7ActionPerformed
        //Nada
    }//GEN-LAST:event_mnCadastro7ActionPerformed

    private void miRefNovaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRefNovaView1ActionPerformed
        RefeicaoNovaController refNovaController = new RefeicaoNovaController(new RefeicaoNovaView());
        refNovaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRefNovaView1ActionPerformed

    private void btnRefeicaoHistoricoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicaoHistoricoView1ActionPerformed
        RefeicaoHistoricoController refHistController = new RefeicaoHistoricoController(new RefeicaoHistoricoView());
        refHistController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRefeicaoHistoricoView1ActionPerformed

    private void miRemRefeicaoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemRefeicaoView1ActionPerformed
        RefeicaoRemoverController refRemController = new RefeicaoRemoverController(new RefeicaoRemoverView());
        refRemController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemRefeicaoView1ActionPerformed

    private void btnRefeicao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicao7ActionPerformed
        //Nada
    }//GEN-LAST:event_btnRefeicao7ActionPerformed

    private void btnRelatorioPessoasView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPessoasView1ActionPerformed
        RelatorioPessoaController relComidaController = new RelatorioPessoaController(new RelatorioPessoaView());
        relComidaController.exibeTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioPessoasView1ActionPerformed

    private void btnRelatorioComidaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioComidaView1ActionPerformed
        RelatorioComidaController relComidaController = new RelatorioComidaController(new RelatorioComidaView());
        relComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioComidaView1ActionPerformed

    private void miCalcImpacView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcImpacView1ActionPerformed
        ImpactoCalcularController impacCalcController = new ImpactoCalcularController(new ImpactoCalcularView());
        impacCalcController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcImpacView1ActionPerformed

    private void miVisualizarImpactoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarImpactoView1ActionPerformed
        ImpactoVisualizarController impacVisuController = new ImpactoVisualizarController(new ImpactoVisualizarView());
        impacVisuController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarImpactoView1ActionPerformed

    private void miCalcularDietaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDietaView1ActionPerformed
        DietaCalcularController dietaCalcularController = new DietaCalcularController(new DietaCalcularView());
        dietaCalcularController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcularDietaView1ActionPerformed

    private void miVisualizarDietaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarDietaView1ActionPerformed
        DietaVisualizarController dietaVisualizarController = new DietaVisualizarController(new DietaVisualizarView());
        dietaVisualizarController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarDietaView1ActionPerformed

    private void miCalcularDieta4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDieta4ActionPerformed
        //Nada
    }//GEN-LAST:event_miCalcularDieta4ActionPerformed

    private void miRankingGeralView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRankingGeralView1ActionPerformed
        RankingGeralController rankingGeralController = new RankingGeralController(new RankingGeralView());
        rankingGeralController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRankingGeralView1ActionPerformed

    private void miRemPesViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemPesViewActionPerformed
        RemoverPessoaController removerPessoaController = new RemoverPessoaController(new RemoverPessoaView());
        removerPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemPesViewActionPerformed

    
    public void adicionarAcaoBuscarRemPes(ActionListener acao){
        btnBuscarRemPesView.addActionListener(acao);
    }
    
    public void exibirTela(){
        setVisible(true);
    }
    
    public String getCategoriaRemPes(){
        return cmbCategoriasRemPesVoew.getSelectedItem().toString();
    }
    
    public int getQtdElemtosCMB(){
        return cmbPessoaRemPesView.getItemCount();
    }
    
    public Object getPessoaRemover(){
        return cmbPessoaRemPesView.getSelectedItem();
    }
    
    public void adicionarAcaoBotaoRemoverPes(ActionListener acao){
        btnRemoverRemPesView.addActionListener(acao);
    }
    
    public String getTextField(){
        return tfRemPesView.getText();
    }
    
    public void addCMBPessoas(Pessoa p){
        cmbPessoaRemPesView.addItem(p);
    }
    
    public void limparCMBPessoa(){
        cmbPessoaRemPesView.removeAllItems();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarRemPesView;
    private javax.swing.JMenuItem btnCadastroComida7;
    private javax.swing.JMenuItem btnCadastroPessoa4;
    private javax.swing.JMenu btnRefeicao7;
    private javax.swing.JMenuItem btnRefeicaoHistoricoView1;
    private javax.swing.JMenuItem btnRelatorioComidaView1;
    private javax.swing.JMenuItem btnRelatorioPessoasView1;
    private javax.swing.JMenu btnRelatório7;
    private javax.swing.JButton btnRemoverRemPesView;
    private javax.swing.JComboBox<String> cmbCategoriasRemPesVoew;
    private javax.swing.JComboBox<Pessoa> cmbPessoaRemPesView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem miCalcImpacView1;
    private javax.swing.JMenu miCalcularDieta4;
    private javax.swing.JMenuItem miCalcularDietaView1;
    private javax.swing.JMenu miCalcularImpacto2;
    private javax.swing.JMenu miRankingGeral4;
    private javax.swing.JMenuItem miRankingGeralView1;
    private javax.swing.JMenuItem miRefNovaView1;
    private javax.swing.JMenuItem miRemPesView;
    private javax.swing.JMenuItem miRemRefeicaoView1;
    private javax.swing.JMenuItem miVisualizarDietaView1;
    private javax.swing.JMenuItem miVisualizarImpactoView1;
    private javax.swing.JMenu mnCadastro7;
    private javax.swing.JMenu mnRemPesView;
    private javax.swing.JTextField tfRemPesView;
    // End of variables declaration//GEN-END:variables
}
