/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import Controller.*;
import DAO.*;
import Exception.*;
import Model.*;
import View.*;
import java.awt.Color;
import javax.swing.ImageIcon;

/**
 *
 * @author Usuário
 */
public class TelaPrincipalView extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipalView
     */
    
    ImageIcon imageHomeScreen = new ImageIcon("WaterAid_v2.jpeg");
    int larguraImage = imageHomeScreen.getIconWidth();
    int alturaImage = imageHomeScreen.getIconHeight();
    
            
    public TelaPrincipalView() {
        initComponents();
        Color backGroundColor=  new Color(221,221,221);
        this.getContentPane().setBackground(backGroundColor);
        jLabel1.setIcon(imageHomeScreen);
        
        getContentPane().add(jLabel1);
        setSize(larguraImage + 20, alturaImage + 70);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnCadastro7 = new javax.swing.JMenu();
        btnCadastroPessoa4 = new javax.swing.JMenuItem();
        btnCadastroComida7 = new javax.swing.JMenuItem();
        btnRefeicao7 = new javax.swing.JMenu();
        miRefNovaView1 = new javax.swing.JMenuItem();
        btnRefeicaoHistoricoView1 = new javax.swing.JMenuItem();
        btnRelatório7 = new javax.swing.JMenu();
        btnRelatorioPessoasView1 = new javax.swing.JMenuItem();
        btnRelatorioComidaView1 = new javax.swing.JMenuItem();
        miCalcularImpacto2 = new javax.swing.JMenu();
        miCalcImpacView1 = new javax.swing.JMenuItem();
        miVisualizarImpactoView1 = new javax.swing.JMenuItem();
        miCalcularDieta5 = new javax.swing.JMenu();
        miCalcularDietaView1 = new javax.swing.JMenuItem();
        miVisualizarDietaView1 = new javax.swing.JMenuItem();
        miRankingGeral4 = new javax.swing.JMenu();
        miRankingGeralView2 = new javax.swing.JMenuItem();
        mnRemPesView1 = new javax.swing.JMenu();
        miRemPesView1 = new javax.swing.JMenuItem();
        miRemRefeicaoView1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuBar1.setBackground(new java.awt.Color(42, 187, 242));

        mnCadastro7.setText("Cadastro");
        mnCadastro7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCadastro7ActionPerformed(evt);
            }
        });

        btnCadastroPessoa4.setText("Cadastro Pessoa");
        btnCadastroPessoa4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroPessoa4ActionPerformed(evt);
            }
        });
        mnCadastro7.add(btnCadastroPessoa4);

        btnCadastroComida7.setText("Cadastro Comida");
        btnCadastroComida7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroComida7ActionPerformed(evt);
            }
        });
        mnCadastro7.add(btnCadastroComida7);

        jMenuBar1.add(mnCadastro7);

        btnRefeicao7.setText("Refeição");
        btnRefeicao7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicao7ActionPerformed(evt);
            }
        });

        miRefNovaView1.setText("Nova Refeição");
        miRefNovaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRefNovaView1ActionPerformed(evt);
            }
        });
        btnRefeicao7.add(miRefNovaView1);

        btnRefeicaoHistoricoView1.setText("Histórico Refeição");
        btnRefeicaoHistoricoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefeicaoHistoricoView1ActionPerformed(evt);
            }
        });
        btnRefeicao7.add(btnRefeicaoHistoricoView1);

        jMenuBar1.add(btnRefeicao7);

        btnRelatório7.setText("Relatório");

        btnRelatorioPessoasView1.setText("Pessoas");
        btnRelatorioPessoasView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioPessoasView1ActionPerformed(evt);
            }
        });
        btnRelatório7.add(btnRelatorioPessoasView1);

        btnRelatorioComidaView1.setText("Comida");
        btnRelatorioComidaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioComidaView1ActionPerformed(evt);
            }
        });
        btnRelatório7.add(btnRelatorioComidaView1);

        jMenuBar1.add(btnRelatório7);

        miCalcularImpacto2.setText("Impacto");

        miCalcImpacView1.setText("Calcular Impacto");
        miCalcImpacView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcImpacView1ActionPerformed(evt);
            }
        });
        miCalcularImpacto2.add(miCalcImpacView1);

        miVisualizarImpactoView1.setText("Visualizar Impacto");
        miVisualizarImpactoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarImpactoView1ActionPerformed(evt);
            }
        });
        miCalcularImpacto2.add(miVisualizarImpactoView1);

        jMenuBar1.add(miCalcularImpacto2);

        miCalcularDieta5.setText("Dieta");
        miCalcularDieta5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDieta5ActionPerformed(evt);
            }
        });

        miCalcularDietaView1.setText("Calcular Dieta");
        miCalcularDietaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCalcularDietaView1ActionPerformed(evt);
            }
        });
        miCalcularDieta5.add(miCalcularDietaView1);

        miVisualizarDietaView1.setText("Visualizar Dieta");
        miVisualizarDietaView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVisualizarDietaView1ActionPerformed(evt);
            }
        });
        miCalcularDieta5.add(miVisualizarDietaView1);

        jMenuBar1.add(miCalcularDieta5);

        miRankingGeral4.setText("Ranking");

        miRankingGeralView2.setText("Ranking Geral");
        miRankingGeralView2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRankingGeralView2ActionPerformed(evt);
            }
        });
        miRankingGeral4.add(miRankingGeralView2);

        jMenuBar1.add(miRankingGeral4);

        mnRemPesView1.setText("Remover");

        miRemPesView1.setText("Remover Pessoa");
        miRemPesView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemPesView1ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemPesView1);

        miRemRefeicaoView1.setText("Remover Refeição");
        miRemRefeicaoView1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miRemRefeicaoView1ActionPerformed(evt);
            }
        });
        mnRemPesView1.add(miRemRefeicaoView1);

        jMenuBar1.add(mnRemPesView1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastroPessoa4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroPessoa4ActionPerformed
        CadastroPessoaController cadPessoaController = new CadastroPessoaController(new CadastroPessoaView());
        cadPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroPessoa4ActionPerformed

    private void btnCadastroComida7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroComida7ActionPerformed
        CadastroComidaController cadComidaController = new CadastroComidaController(new CadastroComidaView());
        cadComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnCadastroComida7ActionPerformed

    private void mnCadastro7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCadastro7ActionPerformed
        //Nada
    }//GEN-LAST:event_mnCadastro7ActionPerformed

    private void miRefNovaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRefNovaView1ActionPerformed
        RefeicaoNovaController refNovaController = new RefeicaoNovaController(new RefeicaoNovaView());
        refNovaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRefNovaView1ActionPerformed

    private void btnRefeicaoHistoricoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicaoHistoricoView1ActionPerformed
        RefeicaoHistoricoController refHistController = new RefeicaoHistoricoController(new RefeicaoHistoricoView());
        refHistController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRefeicaoHistoricoView1ActionPerformed

    private void btnRefeicao7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefeicao7ActionPerformed
        //Nada
    }//GEN-LAST:event_btnRefeicao7ActionPerformed

    private void btnRelatorioPessoasView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioPessoasView1ActionPerformed
        RelatorioPessoaController relComidaController = new RelatorioPessoaController(new RelatorioPessoaView());
        relComidaController.exibeTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioPessoasView1ActionPerformed

    private void btnRelatorioComidaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelatorioComidaView1ActionPerformed
        RelatorioComidaController relComidaController = new RelatorioComidaController(new RelatorioComidaView());
        relComidaController.exibirTela();
        dispose();
    }//GEN-LAST:event_btnRelatorioComidaView1ActionPerformed

    private void miCalcImpacView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcImpacView1ActionPerformed
        ImpactoCalcularController impacCalcController = new ImpactoCalcularController(new ImpactoCalcularView());
        impacCalcController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcImpacView1ActionPerformed

    private void miVisualizarImpactoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarImpactoView1ActionPerformed
        ImpactoVisualizarController impacVisuController = new ImpactoVisualizarController(new ImpactoVisualizarView());
        impacVisuController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarImpactoView1ActionPerformed

    private void miCalcularDietaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDietaView1ActionPerformed
        DietaCalcularController dietaCalcularController = new DietaCalcularController(new DietaCalcularView());
        dietaCalcularController.exibirTela();
        dispose();
    }//GEN-LAST:event_miCalcularDietaView1ActionPerformed

    private void miVisualizarDietaView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVisualizarDietaView1ActionPerformed
        DietaVisualizarController dietaVisualizarController = new DietaVisualizarController(new DietaVisualizarView());
        dietaVisualizarController.exibirTela();
        dispose();
    }//GEN-LAST:event_miVisualizarDietaView1ActionPerformed

    private void miCalcularDieta5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCalcularDieta5ActionPerformed
        //Nada
    }//GEN-LAST:event_miCalcularDieta5ActionPerformed

    private void miRankingGeralView2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRankingGeralView2ActionPerformed
        RankingGeralController rankingGeralController = new RankingGeralController(new RankingGeralView());
        rankingGeralController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRankingGeralView2ActionPerformed

    private void miRemPesView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemPesView1ActionPerformed
        RemoverPessoaController removerPessoaController = new RemoverPessoaController(new RemoverPessoaView());
        removerPessoaController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemPesView1ActionPerformed

    private void miRemRefeicaoView1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miRemRefeicaoView1ActionPerformed
        RefeicaoRemoverController refRemController = new RefeicaoRemoverController(new RefeicaoRemoverView());
        refRemController.exibirTela();
        dispose();
    }//GEN-LAST:event_miRemRefeicaoView1ActionPerformed

    /**
     * @param args the command line arguments
     * @throws Exception.CampoVazioException
     * @throws Exception.CpfInvalidoException
     * @throws Exception.CpfExistenteException
     * @throws Exception.IdadeNegativaException
     * @throws Exception.PesoComidaInvalidoException
     * @throws Exception.ComidaRepetidaException
     */
    public static void main(String args[]) throws CampoVazioException, CpfInvalidoException, CpfExistenteException, IdadeNegativaException, PesoComidaInvalidoException, ComidaRepetidaException {
        
        
        
        Pessoa pesArthurAdm = new Administrador();
        pesArthurAdm.setNome("Arthur Cruz");
        pesArthurAdm.setCpf("74182563969");
        pesArthurAdm.setIdade(19);
        pesArthurAdm.setOrientacaoAlimentar("Carnívoro");
        pesArthurAdm.setTipoPessoa("Administrador");
        PessoaDAO.pessoas.add(pesArthurAdm);     
        
        Pessoa pesDaoraUser = new Usuario();
        pesDaoraUser.setNome("Matheus Daora");
        pesDaoraUser.setCpf("95687234158");
        pesDaoraUser.setIdade(30);
        pesDaoraUser.setOrientacaoAlimentar("Carnívoro");
        pesDaoraUser.setTipoPessoa("Usuario");
        PessoaDAO.pessoas.add(pesDaoraUser);
        
        Pessoa pesBeatrizUser = new Usuario();
        pesBeatrizUser.setNome("Beatriz Souza");
        pesBeatrizUser.setCpf("78532614982");
        pesBeatrizUser.setIdade(20);
        pesBeatrizUser.setOrientacaoAlimentar("Vegano");
        pesBeatrizUser.setTipoPessoa("Usuario");
        PessoaDAO.pessoas.add(pesBeatrizUser);
        
        Pessoa pesCaioUser = new Usuario();
        pesCaioUser.setNome("Caio Silva");
        pesCaioUser.setCpf("85695123648");
        pesCaioUser.setIdade(22);
        pesCaioUser.setOrientacaoAlimentar("Vegetariano");
        pesCaioUser.setTipoPessoa("Usuario");
        PessoaDAO.pessoas.add(pesCaioUser);
        
        
        Comida cBovino = new Carne();
        Comida cPorco = new Carne();
        Comida cAves = new Carne();
        Comida cLeite = new Carne();
        Comida cOvo = new Carne();
        Comida cQueijo = new Carne();
        Comida cPeixe = new Carne();
        Comida cNulo = new Carne();
        
        cBovino.setTipoComida("Carne");
        cBovino.setNome("Vaca");
        cBovino.setRelComidaAgua((float) 15.4);
        cBovino.setDetalheComida("Uso de Técnicas Nocivas");
        
        cPorco.setTipoComida("Carne");
        cPorco.setNome("Porco");
        cPorco.setRelComidaAgua((float) 6);
        cPorco.setDetalheComida("Uso de Técnicas Nocivas");   
        
        cAves.setTipoComida("Carne");
        cAves.setNome("Aves");
        cAves.setRelComidaAgua((float) 4.34);
        cAves.setDetalheComida("100% Natural / Orgânico");
        
        cLeite.setTipoComida("Carne");
        cLeite.setNome("Leite");
        cLeite.setRelComidaAgua((float) 1.02);
        cLeite.setDetalheComida("Uso de Técnicas Nocivas");
        
        cOvo.setTipoComida("Carne");
        cOvo.setNome("Ovo");
        cOvo.setRelComidaAgua((float) 3.30);
        cOvo.setDetalheComida("100% Natural / Orgânico");
        
        cQueijo.setTipoComida("Carne");        
        cQueijo.setNome("Queijo");
        cQueijo.setRelComidaAgua((float) 5.06);
        cQueijo.setDetalheComida("Uso de Técnicas Nocivas");
        
        cPeixe.setTipoComida("Carne");
        cPeixe.setNome("Peixe");
        cPeixe.setRelComidaAgua((float) 2.5);
        cPeixe.setDetalheComida("100% Natural / Orgânico");
        
        cNulo.setTipoComida("Carne");
        cNulo.setNome("Sem Carne");
        cNulo.setRelComidaAgua((float) 0);
        cNulo.setDetalheComida("Nulo");
        
        ComidaDAO.comidas.add(cBovino);
        ComidaDAO.comidas.add(cPorco);
        ComidaDAO.comidas.add(cAves);
        ComidaDAO.comidas.add(cLeite);
        ComidaDAO.comidas.add(cOvo);
        ComidaDAO.comidas.add(cQueijo);
        ComidaDAO.comidas.add(cPeixe);
        ComidaDAO.comidas.add(cNulo);
        
        Comida gArroz = new Grao();
        Comida gMilho = new Grao();
        Comida gFeijao = new Grao();
        Comida gGraoBico = new Grao();
        Comida gLentilha = new Grao();
        Comida gNulo = new Grao();
        
        gArroz.setTipoComida("Grão");
        gArroz.setNome("Arroz");
        gArroz.setRelComidaAgua((float) 2.5);
        gArroz.setDetalheComida("Uso de Técnicas Nocivas");
        
        gMilho.setTipoComida("Grão");
        gMilho.setNome("Milho");
        gMilho.setRelComidaAgua((float) 1.2);
        gMilho.setDetalheComida("100% Natural / Orgânico");
        
        gFeijao.setTipoComida("Grão");
        gFeijao.setNome("Feijão");
        gFeijao.setRelComidaAgua((float) 1.32);
        gFeijao.setDetalheComida("Uso de Técnicas Nocivas");
        
        gGraoBico.setTipoComida("Grão");
        gGraoBico.setNome("Grão de Bico");
        gGraoBico.setRelComidaAgua((float) 4.2);
        gGraoBico.setDetalheComida("Uso de Técnicas Nocivas");
        
        gLentilha.setTipoComida("Grão");
        gLentilha.setNome("Lentilha");
        gLentilha.setRelComidaAgua((float) 5.9);
        gLentilha.setDetalheComida("100% Natural / Orgânico");
        
        gNulo.setTipoComida("Grão");
        gNulo.setNome("Sem Grão");
        gNulo.setRelComidaAgua((float) 0);
        gNulo.setDetalheComida("Nulo");
        
        
        ComidaDAO.comidas.add(gArroz);
        ComidaDAO.comidas.add(gMilho);
        ComidaDAO.comidas.add(gFeijao);
        ComidaDAO.comidas.add(gGraoBico);
        ComidaDAO.comidas.add(gLentilha);
        ComidaDAO.comidas.add(gNulo);
        
        Comida vAlface = new Vegetal();
        Comida vBatata = new Vegetal();
        Comida vTomate = new Vegetal();
        Comida vPepino = new Vegetal();
        Comida vCenoura = new Vegetal();
        Comida vNulo = new Vegetal();
        
        vAlface.setTipoComida("Vegetal");
        vAlface.setNome("Alface");
        vAlface.setRelComidaAgua((float) 0.24);
        vAlface.setDetalheComida("100% Natural / Orgânico");
        
        vBatata.setTipoComida("Vegetal");
        vBatata.setNome("Batata");
        vBatata.setRelComidaAgua((float) 0.30);
        vBatata.setDetalheComida("Uso de Técnicas Nocivas");
        
        vTomate.setTipoComida("Vegetal");
        vTomate.setNome("Tomate");
        vTomate.setRelComidaAgua((float) 0.20);
        vTomate.setDetalheComida("Uso de Técnicas Nocivas");
        
        vPepino.setTipoComida("Vegetal");
        vPepino.setNome("Pepino");
        vPepino.setRelComidaAgua((float) 0.36);
        vPepino.setDetalheComida("Uso de Técnicas Nocivas");
        
        vCenoura.setTipoComida("Vegetal");
        vCenoura.setNome("Cenoura");
        vCenoura.setRelComidaAgua((float) 0.38);
        vCenoura.setDetalheComida("100% Natural / Orgânico");
        
        vNulo.setTipoComida("Vegetal");
        vNulo.setNome("Sem Vegetal");
        vNulo.setRelComidaAgua((float) 0);
        vNulo.setDetalheComida("Nulo");
        
        
        ComidaDAO.comidas.add(vAlface);
        ComidaDAO.comidas.add(vBatata);
        ComidaDAO.comidas.add(vTomate);
        ComidaDAO.comidas.add(vPepino);
        ComidaDAO.comidas.add(vCenoura);
        ComidaDAO.comidas.add(vNulo);
        
        Refeicao refArthur1 = new Refeicao();
        refArthur1.setData("14/09/2022");
        refArthur1.setPessoa(pesArthurAdm);
        refArthur1.setNome("Café da Manhã");
        refArthur1.setTipoCarne((Carne) cOvo);
        refArthur1.setPesoTipoCarne(200);
        refArthur1.setTipoGrao((Grao) gNulo);
        refArthur1.setPesoTipoGrao(0);
        refArthur1.setTipoVegetal((Vegetal) vBatata);
        refArthur1.setPesoTipoVegetal(100);
        RefeicaoDAO.refeicoes.add(refArthur1);
        
        Refeicao refArthur2 = new Refeicao();
        refArthur2.setData("14/09/2022");
        refArthur2.setPessoa(pesArthurAdm);
        refArthur2.setNome("Almoço");
        refArthur2.setTipoCarne((Carne) cBovino);
        refArthur2.setPesoTipoCarne(250);
        refArthur2.setTipoGrao((Grao) gArroz);
        refArthur2.setPesoTipoGrao(250);
        refArthur2.setTipoVegetal((Vegetal) vTomate);
        refArthur2.setPesoTipoVegetal(100);
        RefeicaoDAO.refeicoes.add(refArthur2);
        
        Refeicao refArthur3 = new Refeicao();
        refArthur3.setData("14/09/2022");
        refArthur3.setPessoa(pesArthurAdm);
        refArthur3.setNome("Janta");
        refArthur3.setTipoCarne((Carne) cLeite);
        refArthur3.setPesoTipoCarne(200);
        refArthur3.setTipoGrao((Grao) gMilho);
        refArthur3.setPesoTipoGrao(300);
        refArthur3.setTipoVegetal((Vegetal) vCenoura);
        refArthur3.setPesoTipoVegetal(100);
        RefeicaoDAO.refeicoes.add(refArthur3);
        
        Refeicao refDaora1 = new Refeicao();
        refDaora1.setData("15/09/2022");
        refDaora1.setPessoa(pesDaoraUser);
        refDaora1.setNome("Café da Manhã");
        refDaora1.setTipoCarne((Carne) cPorco);
        refDaora1.setPesoTipoCarne(150);
        refDaora1.setTipoGrao((Grao) gMilho);
        refDaora1.setPesoTipoGrao(100);
        refDaora1.setTipoVegetal((Vegetal) vTomate);
        refDaora1.setPesoTipoVegetal(50);
        RefeicaoDAO.refeicoes.add(refDaora1);
        
        Refeicao refDaora2 = new Refeicao();
        refDaora2.setData("15/09/2022");
        refDaora2.setPessoa(pesDaoraUser);
        refDaora2.setNome("Almoço");
        refDaora2.setTipoCarne((Carne) cAves);
        refDaora2.setPesoTipoCarne(300);
        refDaora2.setTipoGrao((Grao) gGraoBico);
        refDaora2.setPesoTipoGrao(200);
        refDaora2.setTipoVegetal((Vegetal) vAlface);
        refDaora2.setPesoTipoVegetal(100);
        RefeicaoDAO.refeicoes.add(refDaora2);
        
        Refeicao refDaora3 = new Refeicao();
        refDaora3.setData("15/09/2022");
        refDaora3.setPessoa(pesDaoraUser);
        refDaora3.setNome("Café da Tarde");
        refDaora3.setTipoCarne((Carne) cQueijo);
        refDaora3.setPesoTipoCarne(300);
        refDaora3.setTipoGrao((Grao) gArroz);
        refDaora3.setPesoTipoGrao(200);
        refDaora3.setTipoVegetal((Vegetal) vBatata);
        refDaora3.setPesoTipoVegetal(100);
        RefeicaoDAO.refeicoes.add(refDaora3);
        
        Refeicao refCaio1 = new Refeicao();
        refCaio1.setData("11/10/2022");
        refCaio1.setPessoa(pesCaioUser);
        refCaio1.setNome("Café da Manhã");
        refCaio1.setTipoCarne((Carne) cOvo);
        refCaio1.setPesoTipoCarne(350);
        refCaio1.setTipoGrao((Grao) gArroz);
        refCaio1.setPesoTipoGrao(300);
        refCaio1.setTipoVegetal((Vegetal) vBatata);
        refCaio1.setPesoTipoVegetal(150);
        RefeicaoDAO.refeicoes.add(refCaio1);
        
        Refeicao refCaio2 = new Refeicao();
        refCaio2.setData("11/10/2022");
        refCaio2.setPessoa(pesCaioUser);
        refCaio2.setNome("Janta");
        refCaio2.setTipoCarne((Carne) cQueijo);
        refCaio2.setPesoTipoCarne(100);
        refCaio2.setTipoGrao((Grao) gGraoBico);
        refCaio2.setPesoTipoGrao(350);
        refCaio2.setTipoVegetal((Vegetal) vBatata);
        refCaio2.setPesoTipoVegetal(250);
        RefeicaoDAO.refeicoes.add(refCaio2);
        
        Refeicao refBea1 = new Refeicao();
        refBea1.setData("13/10/2022");
        refBea1.setPessoa(pesBeatrizUser);
        refBea1.setNome("Café da Manhã");
        refBea1.setTipoCarne((Carne) cNulo);
        refBea1.setPesoTipoCarne(0);
        refBea1.setTipoGrao((Grao) gArroz);
        refBea1.setPesoTipoGrao(200);
        refBea1.setTipoVegetal((Vegetal) vTomate);
        refBea1.setPesoTipoVegetal(100);
        RefeicaoDAO.refeicoes.add(refBea1);
        
        Refeicao refBea2 = new Refeicao();
        refBea2.setData("13/10/2022");
        refBea2.setPessoa(pesBeatrizUser);
        refBea2.setNome("Almoço");
        refBea2.setTipoCarne((Carne) cNulo);
        refBea2.setPesoTipoCarne(0);
        refBea2.setTipoGrao((Grao) gLentilha);
        refBea2.setPesoTipoGrao(400);
        refBea2.setTipoVegetal((Vegetal) vBatata);
        refBea2.setPesoTipoVegetal(100);
        RefeicaoDAO.refeicoes.add(refBea2);
        
        Refeicao refBea3 = new Refeicao();
        refBea3.setData("13/10/2022");
        refBea3.setPessoa(pesBeatrizUser);
        refBea3.setNome("Café da Tarde");
        refBea3.setTipoCarne((Carne) cNulo);
        refBea3.setPesoTipoCarne(0);
        refBea3.setTipoGrao((Grao) gMilho);
        refBea3.setPesoTipoGrao(200);
        refBea3.setTipoVegetal((Vegetal) vAlface);
        refBea3.setPesoTipoVegetal(50);
        RefeicaoDAO.refeicoes.add(refBea3);
        
        Refeicao refBea4 = new Refeicao();
        refBea4.setData("13/10/2022");
        refBea4.setPessoa(pesBeatrizUser);
        refBea4.setNome("Janta");
        refBea4.setTipoCarne((Carne) cNulo);
        refBea4.setPesoTipoCarne(0);
        refBea4.setTipoGrao((Grao) gLentilha);
        refBea4.setPesoTipoGrao(300);
        refBea4.setTipoVegetal((Vegetal) vCenoura);
        refBea4.setPesoTipoVegetal(50);
        RefeicaoDAO.refeicoes.add(refBea4);
        
        Refeicao refBea5 = new Refeicao();
        refBea5.setData("13/10/2022");
        refBea5.setPessoa(pesBeatrizUser);
        refBea5.setNome("Ceia");
        refBea5.setTipoCarne((Carne) cNulo);
        refBea5.setPesoTipoCarne(0);
        refBea5.setTipoGrao((Grao) gNulo);
        refBea5.setPesoTipoGrao(0);
        refBea5.setTipoVegetal((Vegetal) vBatata);
        refBea5.setPesoTipoVegetal(100);
        RefeicaoDAO.refeicoes.add(refBea5);
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipalView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnCadastroComida7;
    private javax.swing.JMenuItem btnCadastroPessoa4;
    private javax.swing.JMenu btnRefeicao7;
    private javax.swing.JMenuItem btnRefeicaoHistoricoView1;
    private javax.swing.JMenuItem btnRelatorioComidaView1;
    private javax.swing.JMenuItem btnRelatorioPessoasView1;
    private javax.swing.JMenu btnRelatório7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCalcImpacView1;
    private javax.swing.JMenu miCalcularDieta5;
    private javax.swing.JMenuItem miCalcularDietaView1;
    private javax.swing.JMenu miCalcularImpacto2;
    private javax.swing.JMenu miRankingGeral4;
    private javax.swing.JMenuItem miRankingGeralView2;
    private javax.swing.JMenuItem miRefNovaView1;
    private javax.swing.JMenuItem miRemPesView1;
    private javax.swing.JMenuItem miRemRefeicaoView1;
    private javax.swing.JMenuItem miVisualizarDietaView1;
    private javax.swing.JMenuItem miVisualizarImpactoView1;
    private javax.swing.JMenu mnCadastro7;
    private javax.swing.JMenu mnRemPesView1;
    // End of variables declaration//GEN-END:variables
}
